### ISSUE TITLE
How does Accelwattch calculate scheduler power consumption?

### ISSUE THREAD

**Issue by ishitachaturvedi** [accel-sim/accel-sim-framework#103]
I read the paper and went through the code but I cannot understand how the scheduler power consumption is calculated. Please help me out with this. Thank you!

**Comment by JRPan** [comment]
@VijayKandiah Could you please take a look?

**Comment by VijayKandiah** [comment]
The activity factors we use for calculating scheduler power is the number of committed instructions in the INT and FP pipeline (m_num_INTdecoded_insn and m_num_FPdecoded_insn), incremented here https://github.com/accel-sim/gpgpu-sim_distribution/blob/release-accelwattch/src/gpgpu-sim/shader.cc#L858 . The value FP_INT in the xml file corresponds to the weight/scaling factor we apply for scheduler power.

**Comment by rodhuega** [comment]
So if we want to model the difference between using GTO, LRR OLD, WL and TLA, we should change that FP_INT somehow?

**Comment by VijayKandiah** [comment]
You would have to model (analytically or by other means) the relative change in power consumption of your new scheduler and apply that factor to the weight (FP_INT) that corresponds to the scheduler in AccelWattch.
