### ISSUE TITLE
Questions about stat file

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#11]
Hi
After reading the detailed [readme](https://github.com/accel-sim/accel-sim-framework/blob/dev/util/job_launching/README.md), still I have some questions about the stat section. Right now I see something like this:

```
----------------------------------------------------------------------------------------------------
gpu_ipc\s*=\s*(.*)
APPS,RTX2060
cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M--final_kernel,1529.8308

----------------------------------------------------------------------------------------------------
gpu_occupancy\s*=\s*(.*)%
APPS,RTX2060
cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M--final_kernel,89.0889

----------------------------------------------------------------------------------------------------
L2_BW\s*=\s*(.*)+GB\/Sec
APPS,RTX2060
cfd-rodinia-3.1/_GPUAPPS_ROOT_data_dirs_cuda_rodinia_3_1_cfd_rodinia_3_1_data_missile_domn_0_2M--final_kernel,

----------------------------------------------------------------------------------------------------
```

First question is what does an empty L2_BW mean? Kind of error in the middle of simulation? As I checked the log file, I didn't see any error. Where else should I check?

Second question is the unit of IPC. The value is 1529.8308 now. So, should I divide that to a number to get per SM value? It is an aggregate of some things?

Third question is about the results per kernel or aggregation of kernels. For my test, I simulated 5 kernels and got this result. Any note for interpreting that?

**Comment by mkhairy** [comment]
1- Do you see "L2_BW" in the output file? if not, then it is not reported and we should have deleted form the stats.

2- 1529.8308 is the total IPC per all the GPU overall SMs. Not sure why you want to divide it per SM

3- The results here are aggregated over all kernels. If you run ./get_stats command with "-k -K" options it will report results per kernel instance.

**Comment by mahmoodn** [comment]
1- Yes I see that in the output file. 
L2_BW  =     503.8555 GB/Sec
It seems that the regex is not correct for that stat. So it should be 
```
'L2_BW\s*=\s*(.*)\s*GB\/Sec'
```
instead of 
```
'L2_BW\s*=\s*(.*)+GB\/Sec'
```
in example_stats.yml. Now I see
```
L2_BW\s*=\s*(.*)\s*GB\/Sec
APPS,RTX2060
sgemm/a--final_kernel,503.8555
```
Thanks for the hint.

**Comment by mkhairy** [comment]
ok, great, please send a pull request for this. thanks!

**Comment by mahmoodn** [comment]
@mkhairy 
Regarding the IPC, I did a test for Parboil SGEMM with the TITANV config and compared some stats with the nvprof. The results are

accel-sim:
gpu_sim_insn = 1642358784
gpu_ipc =    4098.4072
gpu_occupancy = 37.1880% 
total dram reads = 423578
total dram writes = 60204

and

nvprof:
thread_instruction executed = 1659389952
executed IPC = 2.027
dram_read_transactions = 393250
dram_write_transactions = 121876
achieved_occupancy = 0.4

As you can see some stats are similar. For example, occupancy and dram reads are acceptable. However, the IPC of 4098 is something strange. Even dividing that by the number of SMs (4098/80) the IPC of each SM is 51.
Do you have any note?

**Comment by mkhairy** [comment]
we do not rely on the IPC reported by nvprof, because Nvidia has a different measurement to calculate this, I think this was the issues per cycles per SM, something like that. The way we calculate IPC in accel-sim is the total executed warp instruction in all SMs divided by total instruction. We actually rely on cycles correlation as a good measurement for time simulation. 

Please, refer to the next spreadsheet that contains all the mapping between reported stats in accel-sim, nvprof, and nsight.
https://docs.google.com/spreadsheets/d/1oLbNX-5qTnF9x4v-GCUKuA5zvjx72yD0D2rJIllBHds/edit#gid=0

This is the way we calculate the IPC in the accel-sim paper:
https://github.com/accel-sim/accel-sim-framework/blob/2fa163ab7f4daac2893b34ba54b707de463287a0/util/plotting/correl_mappings.py#L511
