### ISSUE TITLE
TITANX hw_def Core model?

### ISSUE THREAD

**Issue by drajarshi** [accel-sim/accel-sim-framework#119]
Hi
The TITANX hw_def.h file indicates that the core model is subcore (https://github.com/accel-sim/accel-sim-framework/blob/dev/util/tuner/GPU_Microbenchmark/hw_def/pascal_TITANX_hw_def.h).

`#define CORE_MODEL core_model::subcore`

From the file:
`gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM6_TITANX/gpgpusim.config:-gpgpu_sub_core_model 1`

the core model of TITANX is `subcore`.

However, the microbenchmark results (https://docs.google.com/spreadsheets/d/1FlSb6XusECmG-WNSghbGcZuhFFLr4L7d5f1wsOaMFDA/edit?usp=sharing) indicate that the core model for TITANX is `shared`. 

Is the core model `subcore` or `shared`?

Thanks

**Comment by mkhairy** [comment]
TITANX is shared. yes, this is a typo/bug. In the def file, it should be shared. Can you fix that and make PR?

**Comment by drajarshi** [comment]
Thanks for your response.

I would like to make the change and create a PR too. 

However, I am unclear about the concept.
I am unable to figure it out from the documentation and the code comments.

Can you help me understand the `subcore` core model? What exactly is the difference between a `shared` and `subcore` core model?

Would the GP106 have a `shared` or `subcore` core model?

**Comment by drajarshi** [comment]
@mkhairy 
Gentle reminder. Awaiting your inputs to proceed further.

Thanks

**Comment by drajarshi** [comment]
@mkhairy 

I updated my question above. Your inputs please.

**Comment by drajarshi** [comment]
Hi

From the Volta whitepaper,
'the GP100 SM is partitioned into two processing blocks, each with 32
FP32 Cores, 16 FP64 Cores, an instruction buffer, one warp scheduler, two dispatch units, and a
128 KB Register File'.

So, that would mean the GP100 has a separate register file per processing block and it would follow a `subcore` model. Is this understanding correct?

Does a GP100, GP102 (Titan X) and GP106 (Quadro P2200) have the same partitioning within a SM? 

thanks

**Comment by rodhuega** [comment]
The GP102 and GP104 use the sub-core model with 4 subcores.  https://international.download.nvidia.com/geforce-com/international/pdfs/GeForce_GTX_1080_Whitepaper_FINAL.pdf

Page 8 to see GP104.

See here GP102
https://hexus.net/tech/reviews/graphics/95215-nvidia-titan-x-pascal/

**Comment by drajarshi** [comment]
@rodhuega ok thanks. That means the GP102 (Titan X) and GP104 follow a `subcore` model. 

Being a Pascal, it appears that the GP106 has a `subcore` model as well.

I found a picture of the GP106:
![GP106_architecture](https://user-images.githubusercontent.com/22958960/167267009-944f0b75-a8ed-41c8-9efc-f347d5601fed.jpg)

@mkhairy This means the hw_def file is correct in mentioning the core model as `subcore` for TITANX and a PR is not required. Please confirm.
