### ISSUE TITLE
Correctness of IPOLY hashing

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#126]
Hi
The polynomial hashing described is [hashing.cc](hashing.cc) is not very clear. From the  SACAT [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7744628), the index is calculated by 

R(x) = A(x) mod P(x)

For degree 5, the IPOLY(37) is like this

37 -> 1 0 0 1 0 1  (x5+x2+1)

Assume we want to randomize address location 40. So, A(x) is like this

40 -> 101000 (x5+x3)

According to the online [tool](http://www.ee.unb.ca/cgi-bin/tervo/calc.pl?num=101000&den=100101&f=d&e=1&m=1), `101000 mod 100101 = 01101`. So the set index is 13. That means address 40 is mapped to set 13.

However, according to the equations in the code, we get 11100 which is 28.  See:
```
    new_index[0] =
        a[13] ^ a[12] ^ a[11] ^ a[10] ^ a[9] ^ a[6] ^ a[5] ^ a[3] ^ a[0] ^ b[0];
    new_index[1] = a[14] ^ a[13] ^ a[12] ^ a[11] ^ a[10] ^ a[7] ^ a[6] ^ a[4] ^
                   a[1] ^ b[1];
    new_index[2] =
        a[14] ^ a[10] ^ a[9] ^ a[8] ^ a[7] ^ a[6] ^ a[3] ^ a[2] ^ a[0] ^ b[2];
    new_index[3] =
        a[11] ^ a[10] ^ a[9] ^ a[8] ^ a[7] ^ a[4] ^ a[3] ^ a[1] ^ b[3];
    new_index[4] =
        a[12] ^ a[11] ^ a[10] ^ a[9] ^ a[8] ^ a[5] ^ a[4] ^ a[2] ^ b[4];
```
For new_index[0], both a[5] and a[3] exist, so it is zero. You can also check the other bits as well.
Any thoughts about that?

**Comment by mkhairy** [comment]
I would highly encourage you to read the original paper, "Pseudo-Randomly Interleaved Memory," ISCA 1991. But the steps you listed above are wrong, and I do not remember the exact steps as I did that long time ago. The SACAT paper does not have the details too. So, I encourage you to read the original ISCA 91 paper that has more mathematical equations and details on producing these equations.
