### ISSUE TITLE
Activating the debugger information

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#128]
I have done the following things to print more debug information:
1- Source the environment file with `debug` option.
2- Run `-gpgpu_ptx_inst_debug_to_file 1` in the terminal.
3- Add `-gpgpu_ptx_inst_debug_to_file 1` to the config file.
As I run the accelsim command, I see `inst_debug.txt` is created but it remains empty even after the execution finishes. Any other thing to do to increase verbosity?

**Comment by JRPan** [comment]
Hi, I'm not sure why the file is empty, but you may try the tracer (note this is **not** the NVBit tracer we created in Accle-Sim) option. Here is the example config for Volta.
[https://github.com/accel-sim/gpgpu-sim_distribution/blob/7a3fd9a53ec3f86836f417c619172f0b78762e61/configs/tested-cfgs/SM7_QV100/gpgpusim.config#L206-L208](https://github.com/accel-sim/gpgpu-sim_distribution/blob/7a3fd9a53ec3f86836f417c619172f0b78762e61/configs/tested-cfgs/SM7_QV100/gpgpusim.config#L206-L208). Uncomment line 206 to 208 to enable the tracer. Info will be printed via stdout. 

There are also other flags in the tracer you can play with. This will print out pipeline and scheduler details. 
Hope this help. Thanks

**Comment by mahmoodn** [comment]
Right. I was able to see more components based on the list in [trace_streams.tup](https://github.com/accel-sim/gpgpu-sim_distribution/blob/7a3fd9a53ec3f86836f417c619172f0b78762e61/src/trace_streams.tup).

Regarding the zero file `inst_debug.txt`, I searched in the code, and the [fprintf](https://github.com/accel-sim/gpgpu-sim_distribution/blob/7a3fd9a53ec3f86836f417c619172f0b78762e61/src/cuda-sim/cuda-sim.cc#L1798) for that file is called by the upper function [functionalCoreSim::execute()](https://github.com/accel-sim/gpgpu-sim_distribution/blob/7a3fd9a53ec3f86836f417c619172f0b78762e61/src/cuda-sim/cuda-sim.cc#L2562), however, this function is not called by anything, as I look at the code.

**Comment by mahmoodn** [comment]
One more thing. Regarding a debug line like
```
GPGPU-Sim Cycle 5001: WARP_SCHEDULER - Core 0 - Scheduler 0 - scheduler_unit::cycle()
GPGPU-Sim Cycle 5001: WARP_SCHEDULER - Core 0 - Scheduler 0 - Testing (warp_id 0, dynamic_warp_id 0)
GPGPU-Sim Cycle 5001: WARP_SCHEDULER - Core 0 - Scheduler 0 - Warp (warp_id 0, dynamic_warp_id 0) fails as ibuffer_empty
```
I expect this belongs to the first thread block in the trace file
```
#BEGIN_TB

thread block = 0,0,0

warp = 0
insts = 34
0000 ffffffff 1 R1 MOV 0 0 
0010 ffffffff 1 R5 S2R 0 0 
0020 ffffffff 0 ULDC.64 0 0 
0030 ffffffff 0 BSSY 0 0 
0040 ffffffff 1 R0 S2R 0 0 
...
```
Is that right?

**Comment by JRPan** [comment]
> Right. I was able to see more components based on the list in [trace_streams.tup](https://github.com/accel-sim/gpgpu-sim_distribution/blob/7a3fd9a53ec3f86836f417c619172f0b78762e61/src/trace_streams.tup).
> 
> Regarding the zero file `inst_debug.txt`, I searched in the code, and the [fprintf](https://github.com/accel-sim/gpgpu-sim_distribution/blob/7a3fd9a53ec3f86836f417c619172f0b78762e61/src/cuda-sim/cuda-sim.cc#L1798) for that file is called by the upper function [functionalCoreSim::execute()](https://github.com/accel-sim/gpgpu-sim_distribution/blob/7a3fd9a53ec3f86836f417c619172f0b78762e61/src/cuda-sim/cuda-sim.cc#L2562), however, this function is not called by anything, as I look at the code.

Yea this is understandable. Please use the trace option instead. 



> One more thing. Regarding a debug line like
> 
> ```
> GPGPU-Sim Cycle 5001: WARP_SCHEDULER - Core 0 - Scheduler 0 - scheduler_unit::cycle()
> GPGPU-Sim Cycle 5001: WARP_SCHEDULER - Core 0 - Scheduler 0 - Testing (warp_id 0, dynamic_warp_id 0)
> GPGPU-Sim Cycle 5001: WARP_SCHEDULER - Core 0 - Scheduler 0 - Warp (warp_id 0, dynamic_warp_id 0) fails as ibuffer_empty
> ```
> 
> I expect this belongs to the first thread block in the trace file
> 
> ```
> #BEGIN_TB
> 
> thread block = 0,0,0
> 
> warp = 0
> insts = 34
> 0000 ffffffff 1 R1 MOV 0 0 
> 0010 ffffffff 1 R5 S2R 0 0 
> 0020 ffffffff 0 ULDC.64 0 0 
> 0030 ffffffff 0 BSSY 0 0 
> 0040 ffffffff 1 R0 S2R 0 0 
> ...
> ```
> 
> Is that right?

Yes you are correct. `warp_id` should match with the trace file.
