### ISSUE TITLE
Undefined memory access type for async_copy?

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#129]
For one of the cutlass kernels which has LDGSTS instruction (tracer was fine), I get this assertion
```
GPGPU-Sim uArch: Shader 43 bind to kernel 21 '_ZN7cutlass6KernelI67cutlass_tensorop_s1688dgrad_optimized_tf32_256x64_16x4_unity_strideEEvNT_6ParamsE'
thread block = 3,0,0
accel-sim.out: abstract_hardware_model.cc:321: void warp_inst_t::generate_mem_accesses(): Assertion `0' failed.
```
Referring to [mem_access_type](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/src/abstract_hardware_model.cc#L300), is this assertion related to unimplemented instruction in the timing simulation? I think so, but I am not sure. Can someone confirm that this error exists in kernels with LDGSTS instruction?

**Comment by Connie120** [comment]
Yes, this is due to the unimplemented LDGSTS.
