### ISSUE TITLE
CSV file generate by run_hw.py

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#13]
Hi
In the run_hw.py script, I see the output file name as 
```
" | tee " + os.path.join(this_run_dir,logfile + ".nsight")
```
In fact, the actual file name is something like `20.09.25-Friday--16:43:10.csv.nsight` which is a csv file. I wasn't able to open that with the nsight compute program. Instead, I was able to open that csv file with Excel.
So, I want to know if there was any logic behind appending `.nsight` to the file name. Maybe I am missing something.

**Comment by mkhairy** [comment]
hmm, this is just some naming we used to know what tool is used to generate the stats file, nvprof or nsight
