### ISSUE TITLE
Some zero stats

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#131]
Hi
I see some zero stats in the results in both release and dev branches. 
```
gpu_ipc =     456.5914
gpu_tot_sim_cycle = 42811
gpu_tot_sim_insn = 19547136
gpu_tot_ipc =     456.5914
gpu_tot_issued_cta = 1212
gpu_occupancy = 87.8894%
gpu_tot_occupancy = 87.8894%
max_total_param_size = 0
gpu_stall_dramfull = 478461
gpu_stall_icnt2sh    = 0           <======= !
partiton_level_parallism =      10.8712
partiton_level_parallism_total  =      10.8712
partiton_level_parallism_util =      12.7206
partiton_level_parallism_util_total  =      12.7206
L2_BW  =     393.7992 GB/Sec
L2_BW_total  =     393.7992 GB/Sec
gpu_total_sim_rate=444253

========= Core cache stats =========
L1I_cache:
        L1I_total_cache_accesses = 0       <======= !
        L1I_total_cache_misses = 0
        L1I_total_cache_pending_hits = 0
        L1I_total_cache_reservation_fails = 0
L1D_cache:
        L1D_cache_core[0]: Access = 9216, Miss = 9216, Miss_rate = 1.000, Pending_hits = 0, Reservation_fails = 1932
        L1D_cache_core[1]: Access = 9984, Miss = 9984, Miss_rate = 1.000, Pending_hits = 0, Reservation_fails = 1965
        L1D_cache_core[2]: Access = 9984, Miss = 9984, Miss_rate = 1.000, Pending_hits = 0, Reservation_fails = 1849

```
As  you can see L1I stats are all zero. Also, icnt2sh stalls are zero. Since dram stall is not zero, that value is a bit weird.
I tested with some traces and see similar results. This is the output of one of the CFD kernels from rodinia.
Have you seen this before?

**Comment by JRPan** [comment]
Hi, 

by default, we model a perfect inst cache. So all inst loads always hit, therefor no inst cache transaction is generated (`L1I_total_cache_accesses = 0 `). The config option is this one `-gpgpu_perfect_inst_const_cache`. If I-cache is a concern you may disable this flag. The PC in the trace file is used to load insts.

For `gpu_stall_icnt2sh` I think it's irrelevant. 

Thanks
