### ISSUE TITLE
Checkpoing options

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#132]
Hi
I see an empty checkpoint folder with the default settings. Looking at the code, I see the following options:
```
  option_parser_register(opp, "-checkpoint_option", OPT_INT32,
                         &checkpoint_option,
                         " checkpointing flag (0 = no checkpoint)", "0");
  option_parser_register(
      opp, "-checkpoint_kernel", OPT_INT32, &checkpoint_kernel,
      " checkpointing during execution of which kernel (1- 1st kernel)", "1");
  option_parser_register(
      opp, "-checkpoint_CTA", OPT_INT32, &checkpoint_CTA,
      " checkpointing after # of CTA (< less than total CTA)", "0");

```
Assume that there is one kernel (kernel name is kernel-23.traceg) with grid size of (32768,1,1), and I want to create checkpoints every 10K. I want that because the simulation takes a long time. I was wondering if the following options are right for this case:
```
-checkpoint_option 1
-checkpoint_kernel 23
-checkpoint_CTA 10000
```
Any comment about that? 

Edit: How can I resume from checkpoint?

**Comment by JRPan** [comment]
Don't quote me on this. 
We haven't used checkpoints for quite a while. But if it still works, it would be the same as gpgpu-sim. 
You may try their manual on that. I'll ask some folks if they have more info on this. But don't count on that. 

Thanks
