### ISSUE TITLE
Tracer NVBit assertion error

### ISSUE THREAD

**Issue by JRPan** [accel-sim/accel-sim-framework#133]
OP: https://groups.google.com/g/accel-sim/c/v-9BdTu51fk

The error is 
```
tracer_tool.cu:428: void nvbit_at_cuda_event(CUcontext, int, nvbit_api_cuda_t, const char*, void*, CUresult*): Assertion `cudaGetLastError() == cudaSuccess' failed.
```
The benchmark is https://github.com/lienliang/Pair-HMM-Parallel-Programming
This has been tested it on both release and dev branch, also with Nvbit 1.5.3 and 1.5.5.

**Comment by sxzhang1993** [comment]
Hello, thank you for opening this issue.

I was using the RTX3070.

**Comment by JRPan** [comment]
Hi, 

I tried to run this, but I could not find any info on how to build it. I tried the `./test` but failed. 
Are you sure this app is running without erro on your machine? 
If yes, do you know how to build it? I can try if that will make the error go away.

Thanks

```
pan251@tgrogers-gpu01:Pair-HMM-Parallel-Programming$ ./test
2
from_read  41
from_hap  41
from_read  41
from_hap  41
rs_len41
rs_len41
Start Kernel
Done Initialization
Done Initialization
Copy Back Result
pair HMM took 175.896 milliseconds
result : 0
2
from_read  41
from_hap  41
from_read  41
from_hap  41
rs_len41
rs_len41
GPUassert: an illegal memory access was encountered ForwardDiagonalPipeline.cu 404
```

**Comment by sxzhang1993** [comment]
Hello,

I just run the compile.sh and then run the ./test, there is no error messages.

```
root@C.5324820:~/Pair-HMM-Parallel-Programming$ ./test

from_read  41
from_hap  41
from_read  41
from_hap  41
 num of batch in current stream: 2

Start Kernel
Copy Back Result
pair HMM took 0.387627 milliseconds
from_read  41
from_hap  41
from_read  41
from_hap  41
 num of batch in current stream: 2

Start Kernel
Copy Back Result
pair HMM took 0.366177 milliseconds
from_read  41
from_hap  41
from_read  41
from_hap  41
 num of batch in current stream: 2

Start Kernel
Copy Back Result
pair HMM took 0.366146 milliseconds
```

**Comment by JRPan** [comment]
Okay, my bad. Didn't see there is a compile script. 

I was able to recreate your error on a 3070. But it's working fine on a Volta Tesla. 
So something special about Ampere broke it. I'll ask someone to look at it. 

Thanks,
Junrui

**Comment by sxzhang1993** [comment]
Thanks so much for the information!

**Comment by sxzhang1993** [comment]
Hello, now I can get the trace files with Tesla V100, but it will have Segmentation fault when processing the traces, could you also please have a look on this issue?

`~/accel-sim-framework/util/tracer_nvbit/tracer_tool/traces-processing/post-traces-processing traces/kernelslist
`
```
Processing file traces/kernel-1.trace
Segmentation fault (core dumped)
```

**Comment by JRPan** [comment]
We have not seen this before. You can try gdb to see where the error is. That should be straight-forward. If you cannot figure it out, I would need more info on how to re create the error. 

Thanks,
