### ISSUE TITLE
F2FP instruction

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#136]
In a kernel with this line of instruction
```
1720 ffffffff 1 R9 F2FP.PACK_AB 2 R255 R11 0
```
The simulation fails with this message
```
ERROR:  undefined instruction : F2FP.PACK_AB Opcode: F2FP
accel-sim.out: trace_driven.cc:205: bool trace_warp_inst_t::parse_from_trace_struct(const inst_trace_t&, const std::unordered_map<std::__cxx11::basic_string<char>, OpcodeChar>*, const trace_config*, const kernel_trace_t*): Assertion `0 && "undefined instruction"' failed.
```

As I look into the code, I see `UF2FP` as below
```
./ISA_Def/accelwattch_component_mapping.h:    {OP_UF2FP, FP__OP},
./ISA_Def/ampere_opcode.h:    {"UF2FP", OpcodeChar(OP_UF2FP, SPECIALIZED_UNIT_4_OP)},
./ISA_Def/trace_opcode.h:  OP_UF2FP,

```
Also, the ISA [reference ](https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#ampere)has `UF2FP` and not `F2FP` alone. So, I was wondering it replacing `F2FP` with `UF2FP` is a solution for that. Any idea about that?

**Comment by JRPan** [comment]
This looks weird. I cannot get any info on this inst either. I cannot comment on replacing `F2FP` with `UF2FP`. But it should work if you replace it. It's just the timing model may not be accurate. If this inst is not used a lot, then it should have minor effects on your stats. 
You can try posting this issue at NVbit, or the Nvidia forum. 
May I ask what is your workload? 
Thanks.

**Comment by mahmoodn** [comment]
This is kernel-60 from MLPerf/3d-unet. I will close it as I also think it is more related to nvbit.
