### ISSUE TITLE
Difference between accel-sim and nsight results

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#14]
Hi
I ran the Parboil SGEMM and tried the correlation command. In the simulation I see:

total dram reads = 1,922,292
total dram writes = 113,352
gpu_sim_cycle = 838,643
gpu_sim_insn = 1,642,358,784

However, the output of nsight profiler is

dram__sectors_read.sum = 480,475
dram__sectors_write.sum = 84,803
sm__cycles_elapsed.sum = 44,335,166
gpc__cycles_elapsed.avg = 651,864.33
smsp__inst_executed.sum = 51,327,936

The differences are quite large. The commands are
```
./util/job_launching/run_simulations.py -B sgemm -C RTX2060 -T ./hw_run/traces/device-0/10.1/ -N test_sgemm -l local
./util/hw_stats/run_hw.py -B sgemm --nsight_profiler --disable_nvprof
```

Any idea about that?

**Comment by mkhairy** [comment]
Hello Mahmoud, which traces version did you use? the Volta traces or you generated Truing traces of sgemm by yourself?

**Comment by mahmoodn** [comment]
I generated the trace (it is only one kernel) on a 2080Ti.
The config file is for 2060 and it is acceptable to see some differences, however, I guess if I use nsight compute on a 2060 and compare it with 2080ti, the hardware results are nearly the same. On the other hand, I guess nvidia use some special specs in its 'Ti' version and maybe the results of 2060 and 2080Ti are really different.

**Comment by mkhairy** [comment]
The two cards have to be the same, the hardware and the simulator config. 
The 2060 has a completely different configuration than the 2080ti (number of SMs , L2 and memory BW) which affects the reported stats. 
Please, see this Wikipedia page for complete specs:
https://en.wikipedia.org/wiki/GeForce_20_series

**Comment by mahmoodn** [comment]
OK. I will try to modify the the 2060 config file to be similar with 2080Ti and come back later.

**Comment by mkhairy** [comment]
Also, one more thing to add here, Accel-Sim is already coming with a correlation tool that can be used to automatically does all these hardware correlations for you. For further details, please see the section "3- Accel-Sim Correlator" on the readme file of the accel-sim, as well as the plotting folder in util:
https://github.com/accel-sim/accel-sim-framework/tree/release/util/plotting

**Comment by mahmoodn** [comment]
Thank you. I guess the most reliable device config is QV100 at the moment.
