### ISSUE TITLE
ERROR:  undefined instruction : F2FP.PACK_AB Opcode: F2FP

### ISSUE THREAD

**Issue by gty111** [accel-sim/accel-sim-framework#142]
When I run [this program](https://github.com/NVIDIA/cutlass/blob/v2.10.0/examples/41_multi_head_attention/), I meet this problem.
Hope to implement this instruction. Thanks very much.

**Comment by JRPan** [comment]
duplicated with #136 . We were unable to find documentation on what this instruction does. Please let us know if you have any relevant info on it.

Thanks
