### ISSUE TITLE
Issue about using traces generated from 2080Ti-GPU to simulate QV100

### ISSUE THREAD

**Issue by ConvolutedDog** [accel-sim/accel-sim-framework#144]
Hi, I attempt to use the Nvidia 2080Ti GPU to generate the traces of `rodinia-2.0-ft`, and then let GPGPU-sim to run the simulations with the QV100 configurations that your repository provides.

And, the GPGPU-sim prompts the failure of the assertion in line-1424 of `$AccelSimROOT/gpu-simulator/gpgpu-sim/src/gpgpu-sim/shader.cc`, like this,
```
accel-sim.out: shader.cc:1425: void scheduler_unit::cycle(): Assertion `spec_id < m_shader->m_config->m_specialized_unit.size()' failed.
/home/masa/Github/accel-sim-framework/util/job_launching/../../sim_run_11.5/streamcluster-rodinia-2.0-ft/3_6_16_1024_1024_100_none_output_txt_1___data_result_3_6_16_1024_1024_100_none_1_txt/QV100-SASS/slurm.sim: line 52: 2219934 Aborted                 (core dumped) 
/home/masa/Github/accel-sim-framework/util/job_launching/../../sim_run_11.5/gpgpu-sim-builds/accelsim-commit-2260456ea5e6a1420f5734f145a4b7d8ab1d4737_modified_3.0/accel-sim.out -config ./gpgpusim.config -trace ./traces/kernelslist.g
```
and the source code in `shader.cc` is,
```
assert(spec_id < m_shader->m_config->m_specialized_unit.size());
```

But if I use the pre-generated traces that downloaded from `ftp.ecn.purdue.edu`, the GPGPU-sim works well.

I want to confirm that if or not, this issue about `spec_id` is because that the traces I use are not generated from QV100?

Thanks for your reply!

**Comment by JRPan** [comment]
This indeed looks like some config error. Different GPUs has different specialized unit count, and this is specified by the config file. You need to generate traces with a Volta GPU. Or run your 2080Ti traces with a Turing config. 

Thanks

**Comment by Rhythmicc** [comment]
I have a similar problem, have you solved it? Is it that the QV100 can only emulate traces generated by the V100?

**Comment by ConvolutedDog** [comment]
> I have a similar problem, have you solved it? Is it that the QV100 can only emulate traces generated by the V100?

Yeah, the GV100 configuration file (including the instruction category, initial interval, latency, etc.) used by Accel-Sim only contains the SASS instructions generated by the true GV100 GPU, so it can only accept traces generated by GV100. 

If you want to simulate traces generated by non-GV100 GPUs, I suggest that you compare the instructions in the generated trace with the `accel-sim-framework/gpu-simulator/ISA_Def/volta_opcode.h` file and the `accel-sim-framework/gpu-simulator/ISA_Def/accelwattch_component_mapping.h` file and add the missing instructions to the two files, although this is a bit of a hassle.

Another solution is that if you use a Turing GPU, you can merge the above two configuration files of the Turing architecture into the configuration files of the Volta architecture.

**Comment by Ins1s10ce** [comment]
Sorry to bother. I have the same issue when I use the trace generated by tesla-v100 from `ftp.ecn.purdue.edu` and run `./run_simulations.py -B parboil -T ../../hw_run/ -C QV100-SASS-VISUAL -N test2`:
``accel-sim.out: shader.cc:1489: void scheduler_unit::cycle(): Assertion `spec_id < m_shader->m_config->m_specialized_unit.size()' failed.``
It works fine with rodinia-3.1 using the same command: `./run_simulations.py -B rodinia-3.1 -T ../../hw_run/ -C QV100-SASS-VISUAL -N test1`
The machine has RTX 3090 GPU and the docker environment is from `https://github.com/cesar-avalos3/micro-2021-artifact/blob/main/Dockerfile.gpu`
Any ideas about what's going wrong? Thanks for your help!
