### ISSUE TITLE
LDGSTS hasn't set attribute "type of space"

### ISSUE THREAD

**Issue by gty111** [accel-sim/accel-sim-framework#150]
When simulating a program, I met `assert(0)` at `abstract_hardware_model.cc:321`. I tried to figure it out and found LDGSTS is a LOAD_OP but hasn't set attribute `type of space` at `trace_warp_inst_t::parse_from_trace_struct`. So it triggered that error. I think it is easy to fix(just set `type of space` for LDGSTS). Am I right? Looking forward to your reply.

**Comment by JRPan** [comment]
We have not yet implement LDGSTS in the simulation model. We only updated the tracer to trace it. We are still working on that.

Does setting the type solve the problem? Does it make any difference? 

Thanks,
JR

**Comment by gty111** [comment]
Setting the type do solve the assertion error at [here](https://github.com/accel-sim/gpgpu-sim_distribution/blob/dev/src/abstract_hardware_model.cc#L321).  The only difference is letting accel sim deal with LDGSTS just like LDS instead of doing nothing. So it can avoid assertion error. I didn't take into other details into count. Hope to implement LDGSTS in near future.

**Comment by JRPan** [comment]
Yes, that sounds reasonable (and also what I speculated). 

Thanks. Feel free to reopen this if needed.
JR
