### ISSUE TITLE
L2_total_cache_accesses

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#156]
Hi
It seems that the L2 accesses count is questionable. I did a test, by adding two printf statements:

gpu-cache.cc
```
enum cache_request_status tag_array::access(new_addr_type addr, unsigned time,
                                            unsigned &idx, bool &wb,
                                            evicted_block_info &evicted,
                                            mem_fetch *mf) {
  m_access++;
  is_used = true;
  printf("[gpu-cache.cc] %llu %llx\n",    time,    mf->get_addr());
  fflush(stdout);
```
and

l2cache.cc
```
      if (!output_full && port_free) {
        std::list<cache_event> events;
        enum cache_request_status status =
            m_L2cache->access(mf->get_addr(), mf,
                              m_gpu->gpu_sim_cycle + m_gpu->gpu_tot_sim_cycle +
                                  m_memcpy_cycle_offset,
                              events);
        printf("[l2ache.cc] %llu %llx\n",
                m_gpu->gpu_sim_cycle + m_gpu->gpu_tot_sim_cycle,      mf->get_addr());
        fflush(stdout);


```
I expect that total `[l2ache.cc]` printf instances is the same as `L2_total_cache_accesses` in the statistics. However, in the attached output file, you will see `L2_total_cache_accesses = 30520` and 
```
$ grep "\[l2cache.cc\]" output.txt | wc -l
30764
```
Although the difference is small in this example, the kernel simulation finishes successfully. So all pending stats should be finalized before the end of simulation. 
I see that all block addresses in `[l2cache.cc]` lines have an instance of `[gpu-cache.cc]` with the same block address in the previous line. So, the order is indeed correct.
Any idea about that?
[output.txt](https://github.com/accel-sim/accel-sim-framework/files/10522334/output.txt)

**Comment by JRPan** [comment]
To Be Honest, I noticed something similar in my research also. HAHA. 
I wondered if this could be related to the non-deterministic behavior mentioned here, #60. But I haven't tested it very much. 

What I found so far (for my case) is L1 hits are not the same for some of my runs. An L1 hit will filter out the access and not go to L2. Only L1 misses are going to L2. So more miss in L1 causes more L2 access.
Can you check if the total L1 access is the same and also L1 hit/miss (Total_core_cache_stats_breakdown*)? Total L1 accesses should be the number of loads from the traces, so that must be the same. 

Thanks,
JR

**Comment by JRPan** [comment]
Actually, it could be hard to find L1 stats as they are per SM. Could you try disabling L1 and see what happens?
i think this flag `gpgpu_gmem_skip_L1D`

**Comment by mahmoodn** [comment]
From the statistics, we see

```
L1I_total_cache_accesses = 0
L1C_total_cache_accesses = 0
L1T_total_cache_accesses = 0
L1D_total_cache_accesses = 31740
L1D_total_cache_pending_hits = 1200
L1D_total_cache_misses = 30500
L2_total_cache_accesses = 30520
```
Also
```
$ grep "\[l2cache.cc\]" output.txt | wc -l
30764
$ grep "\[gpu-cache.cc\]" output.txt | wc -l
62260

```

Even when we look at the provided stats, L1D misses is not the same as L2 accesses.
What are the pending hits? I was thinking that 30500+1200=31700. There is also 20 difference between the L1D misses and L2 accesses. Then 31700+20=31720 which is close to 31740 but still 20 is missing (!)

Still 62260 instances of [gpu-cache.cc] is weird.

Another thing is that cycle numbers are different. See line 1121-1122 in the output file which is
```
[gpu-cache.cc] 117034 7f674e000400
[l2cache.cc] 6382 7f674e000400
```
The second argument in `access()` is `time` which is actually `m_gpu->gpu_sim_cycle + m_gpu->gpu_tot_sim_cycle`. I was wondering why cycles are different in the output file?

**Comment by mahmoodn** [comment]
I have created a simple case with small numbers where L1D and L2 stats are weird. Since I don't want to mess this topic, I will continue with a new one.
https://github.com/accel-sim/accel-sim-framework/issues/157

I will later reopen this issue it needed.

**Comment by mahmoodn** [comment]
I found the source of difference. Apparently, not all access calls in l2cache.cc
```
      if (!output_full && port_free) {
        std::list<cache_event> events;
        enum cache_request_status status =
            m_L2cache->access(mf->get_addr(), mf,
                              m_gpu->gpu_sim_cycle + m_gpu->gpu_tot_sim_cycle +
                                  m_memcpy_cycle_offset,
                              events);
        printf("[l2ache.cc] %llu %llx\n",
                m_gpu->gpu_sim_cycle + m_gpu->gpu_tot_sim_cycle,      mf->get_addr());
        fflush(stdout);
```
go to the access() function which finds hit/miss. In case of mshr fails in the intermediate functions, final access() is not called. So, printing the block address in l2cache.cc is not correct.

**Comment by JRPan** [comment]
Okay. Glad you sorted everything out. I actually did not know that. 
Thanks for letting me know.
