### ISSUE TITLE
Zero stats for L1I_cache

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#16]
Hello
I have noticed that L1I_cache stats for config files that I have tested (QV100 and 2060) are always zero.
```
gpu_tot_occupancy = 32.3427% 
max_total_param_size = 0
gpu_stall_dramfull = 4253
gpu_stall_icnt2sh    = 0
partiton_level_parallism =      24.5042
partiton_level_parallism_total  =      24.5042
partiton_level_parallism_util =      25.1316
partiton_level_parallism_util_total  =      25.1316
L2_BW  =     887.6406 GB/Sec
L2_BW_total  =     887.6406 GB/Sec
gpu_total_sim_rate=477568

========= Core cache stats =========
L1I_cache:
	L1I_total_cache_accesses = 0
	L1I_total_cache_misses = 0
	L1I_total_cache_pending_hits = 0
	L1I_total_cache_reservation_fails = 0
```
So, I wonder if that is a stale stat in the code, or I have to do some manipulations for that. 
Have you seen that before?

**Comment by mkhairy** [comment]
Hello,
The L1I is the instruction cache. In this config, we assume perfect L1I cache, in which all the instructions are hit in the L1I cache, as we observe something similar in the hardware. If you want to assume normal L1 instruction cache, change "gpgpu_perfect_inst_const_cache" config parameter to 0.

**Comment by mahmoodn** [comment]
Thanks.
