### ISSUE TITLE
undefined symbol: _ZTI12cache_config

### ISSUE THREAD

**Issue by beneslami** [accel-sim/accel-sim-framework#176]
Hi all,

I tried to run backprop-rodinia-2.0-ft but it showed "undefined symbol: _ZTI12cache_config". I double checked the environment variables but they are OK. Any idea about what the problem might be?

Thanks
Ben

**Comment by JRPan** [comment]
I cannot think of another reason other than environmental variables. Maybe you can try make clean and build again? For me, it always is the shared library problem. Double check `LD_LIBRARY_PATH` by running `env`. 

Or you can try run `ldd ./gpu-simulator/bin/release/accel-sim.out` and check for `libcudart.so`. It should link to the one under `accel-sim-framework/gpu-simulator/gpgpu-sim/lib/gcc-7.5.0/cuda-11000/release/libcudart.so`. Make sure the file is there. 

Thanks,
JR

**Comment by lingda-li** [comment]
I had the same problem. It seems conda messes up the version of libcudart.so which gets linked. Deactivating conda and switching to the dev branch solve the problem for me.
