### ISSUE TITLE
the difference between the true card and accel-sim

### ISSUE THREAD

**Issue by MWHYNOT** [accel-sim/accel-sim-framework#191]
Excuse me, when i tried to run the SASS-level in the accel-sim , i found that the " total_insts"in the "/traces/stats.csv" is different from the "gpu_sim_insn"in the Output files.
For example ,in bfs-rodinia-2.0-ft , the " total_insts" of the kernel-1.trace is 1789, but "gpu_sim_insn" of the same kernel in the Output files is 41210, i really wonder why these two data are different, thank you in advance!

**Comment by JRPan** [comment]
I think one is warp inst (1789), and the other one is thread inst (41210). 

Thanks

**Comment by MWHYNOT** [comment]
I have searched the parameter"gpu_sim_insn"in the source code, and find it is indeed thread inst, thanks again for your help!
