### ISSUE TITLE
Observing half Accelsim DRAM bandwidth compare to native

### ISSUE THREAD

**Issue by expgpgpu** [accel-sim/accel-sim-framework#198]
Hi, I am running mem_bw workload of GPU_microbenchmark in PTX mode with latest Accelsim code and observing half dram bandwidth with respect to numbers mentioned in Accel-sim ISCA paper.

run command,
./util/job_launching/run_simulations.py -B GPU_Microbenchmark -C QV100-PTX -N myTest-PTX

gpgpusim configuration,
QV100-PTX

run logs,
Mem BW= 345.807312 (Byte/Clk)
Mem BW= 0.000081 (GB/sec)
**Total Clk number = 582193**
gpu_tot_sim_cycle = 588514
gpu_tot_sim_insn = 72515584

In Paper (**page-10 TABLE VIII**) mentioned mem_bw Hw cycles = 382171 and expecting **16 %** Accel-Sim error. But I am observing **52 %** Accel-sim error (Total Clk number = 582193). Can you please guide me through if anything missing in observation or to improve dram bandwidth?

**Comment by yechen3** [comment]
The clock domain in gpgpusim.config was changed after the paper. You can see the change [here](https://github.com/accel-sim/gpgpu-sim_distribution/compare/84c4f46..e466afb#diff-786c3a4c5eca12eb85cd81175de946c21887d61ac442d0ca1c4f0785d6148654)

**Comment by JRPan** [comment]
We are working on that. For now, please use the this config, which should be able to recreate the results in the paper.
https://github.com/accel-sim/gpgpu-sim_distribution/blob/a8256e50a6d25338f659da76ff9c3595132f54b2/configs/tested-cfgs/SM7_QV100/gpgpusim.config

Thanks
