### ISSUE TITLE
Issues when tracing polybench-2DConvolution

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#2]
Thank you for opening accelsim.

I'm struggling to export tracing files by using 'tracer_nvbit'.

However, the following issue arises when trying to export 2DConvolution's trace files. (CoMD in proxy-app also generates following error.)

![image](https://user-images.githubusercontent.com/14326227/90022252-47e87d00-dced-11ea-9547-212cbc837f1e.png)

In addition, this issue is not handled in NVBit offical github.

Are there any discussions on above issue?

I'm using CUDA 10.1.

**Comment by tgrogers** [comment]
Hi,

This error typically occurs if you are trying to generate a trace and GPGPU-Sim is in your ld_library_path. Please make sure you are using cudart that uses the silicon gpu.

**Comment by allencho1222** [comment]
> Hi, This error typically occurs if you are trying to generate a trace and GPGPU-Sim is in your ld_library_path. Please make sure you are using cudart that uses the silicon gpu.
> […](#)
> Sent from my iPhone
> On Aug 12, 2020, at 09:45, allen ***@***.***> wrote: ﻿ I'm struggling to export tracing file by using 'tracer_nvbit'. However, the following issue arises when trying to export 2DConvolution's trace files. In addition, this issue is not handled in NVBit offical github. Why this happens? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you @tgrogers . I've not noticed it before.

Now, it works correctly.
