### ISSUE TITLE
tracer issues out-of-range errors when tracing conv_bench

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#23]
While gemm_bench and rnn_bench are traced without errors, the tracer throws out-of-range errors when tracing conv_bench in DeepBench.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

run.sh: line 2: 225874 Aborted                 LD_PRELOAD=/trace/util/tracer_nvbit/tracer_tool/tracer_tool.so /gpu-app-collection/bin/10.1/release/conv_bench inference half 700 161 1 1 32 20 5 0 0 2 2

```

It seems that the error occurs when the arguments of the program is parsed.

The program itself runs correctly when the tracer is not used.

**Comment by mkhairy** [comment]
hmm, this looks weird. Do you run multiple workloads tracing at the same time? This may happen if you trace multiple applications at the same time and the traces consume large memory resources. So, when another tracer is running, some trivial allocation of the argument like this may fail. please, run the workload individually and see.

**Comment by mkhairy** [comment]
hmm, wait, sorry, I did not notice it is "out-of-range" error. This means something else. 
May I know what is your runtime configuration? CUDA version, hardware, cuDNN, etc. 
Also, Is the input size you are using have already been traces generated in our accel-sim pre-generated traces?

**Comment by allencho1222** [comment]
The input size is same as the one in the define-all-apps.yaml, which is
conv_bench inference half 700 161 1 1 32 20 5 0 0 2 

CUDA version: 10.1, cuDNN version: 7.6.4.38, GPU: 2080 Ti, NVBit 1.5, which is intergrated in the release version of accelsim

**Comment by mkhairy** [comment]
Is this the only input size that fails? have you tried other input? Are you able to run this input size alone on hardware without the tracer? 
On our side, we are able to generate traces for this particular input. 
We used CuDNN 8.0.4 and Volta V100 card, however, I do not think this should have any impact?

**Comment by allencho1222** [comment]
@mkhairy I only tried non-tensor version. All the input arguments in define-all-apps.yaml fails (rnn and gemm work correctly but, only conv fails). Without tracer, conv_bench runs correctly.  Did you use nvbit 1.5?

**Comment by mkhairy** [comment]
yes, we used Nvbit 1.5. 
Please, try the tensor version and see what happens. Also, try the Volta card if you have any. See if it is a card problem?
We may not have faced this problem as we have not traced the Turing card yet. We only generate traces for Volta till now.

**Comment by mkhairy** [comment]
Can you also send me the exact line where the assertion happens in the deepbench code?

**Comment by allencho1222** [comment]
@mkhairy The issue arises at `cudnnCNN<T1, T2> cnn() `in the function, `time_cnn()`. I coudn't figure out whether the problem is cuDNN version or not. But **conv bench** runs correctly when the tracer does not run (When LD_PRELOAD is not used).

**Comment by mkhairy** [comment]
Please, try the tensor version and see what happens. Also, try the Volta card if you have any. See if it is a card problem?
We may not have faced this problem as we have not traced the Turing card yet. We only generate traces for Volta till now.

**Comment by mkhairy** [comment]
Hi, my labmate has faced a similar problem in other workloads from rodinai-3.1 and Parboil when he moved to CUDA 11.0.
So it seems Nvbit 1.5 has some issues with CUDA 11. He posted the issue to the Nvbit team below. You can follow this issue for further details about this. For now, you can downgrade your CUDA version to 10 or 9 which I think should help to overcome this issue.

https://github.com/NVlabs/NVBit/issues/32
