### ISSUE TITLE
It seems that the address range is too big to map to the global memory address

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#24]
One of the addresses generated from the tracer is:

0x7fd312800004

If this addresses is translated into binary, it is:

0b11111111101001100010010100000000000000000000100

However, it is so big that GPGPU-sim can't map to global memory address mapping, which is:

-gpgpu_mem_addr_mapping dramid@8;00000000.00000000.00000000.00000000.0000RRRR.RRRRRRRR.RBBBCCCB.CCCSSSSS

As shown in 'gpgpu_mem_addr_mapping', GPGPU-sim can't map correct row address. 

For this reason, memory coalescer in GPGPU-sim truncates the upper 32 bits and only uses lower 32bits.
(by using `unsigned block_address = line_size_based_tag_func()`)

However, If use truncated addresses, they cause different addresses to map to the same address, which is incorrect simulation.
(e.g., assuming lower 4 bits are used, 1111**0010** and 0101**0010** map to the same address, **0010**)

**Comment by mkhairy** [comment]
Hi, good observation! May I ask you which workload is this? and how big is your input size? The scenario you described is very unlikely to happen in our simulated workload unless you have a big structure larger than 4 GB that is accessed by threads, and the distance between the threads in the same warp is larger than 4GB.

**Comment by allencho1222** [comment]
I did not directly see the scenario. I just found that the higher bits of the address were truncated by printing the addresses.

But, one of my colleague said that applications from other repositories had this issue.

It seems that accelsim needs to implement page table mechanism later, which is already implemented in nvidia GPU.

**Comment by mkhairy** [comment]
Yes, I see. I think you can easily fix that by making block_address to be new_addr_type (unsigned long long )
Interestingly, subwarp_transactions are already using new_addr_type as a key, so the author of this code did not notice and this was a bug.

```
  std::map<new_addr_type, std::list<transaction_info> >
        subwarp_transactions;  // each block addr maps to a list of transactions

.....

 subwarp_transactions[block_address].push_back(transaction_info());
```

If you fix it, please make PR and I will accept it. Please make the PR in the gpgpu-sim repo dev branch in our accel-sim shown below.
https://github.com/accel-sim/gpgpu-sim_distribution
