### ISSUE TITLE
Run Simulation on Modern Version of PyTorch in AccelSim

### ISSUE THREAD

**Issue by wuliJerry** [accel-sim/accel-sim-framework#248]
Hi there! Thanks for developing the Accelsim framework.

I was wondering how I can run a simulation on a more modern version (compared to the official version of [PyTorch](https://github.com/gpgpu-sim/pytorch-gpgpu-sim) provided by the gpgpu-sim team) using AccelSim and GPGPU-Sim. 

Based on the relevant context provided by the original repo of GPGPU-Sim, it seems like there are a few PyTorch paths that need to be specified in the environment. Yet, I am not sure about how it works on a recent-published and pre-built version from a package manager (like conda or pip) of PyTorch.

Thanks for your help in advance!

FYI: The docker image provided in the README in this repo is used.

**Comment by cesar-avalos3** [comment]
Hello, yes, newer versions of pytorch work in trace mode, both pip and conda-installed work just fine.
#238 has a good example of setting up a quick pytorch test (the part where they mention "define-all-apps.yml") and obtaining the traces for it. Apart from this yml configuration file, there is no other configuration or environment variable that needs to be defined.

**Comment by wuliJerry** [comment]
Hi there! Thanks for your reply!

In this thread, they mentioned `CUDA_INJECTION64_PATH` and `LD_PRELOAD`. Do I need to manually specify these two variables for my Pytorch script?

**Comment by cesar-avalos3** [comment]
Hello, the "run_hw_trace.py" script sets those up for you.

**Comment by wuliJerry** [comment]
Thanks, that works for me!
