### ISSUE TITLE
Some questions of MEM_ACCESS_TYPE_TUP_DEF

### ISSUE THREAD

**Issue by ConvolutedDog** [accel-sim/accel-sim-framework#252]
Hi, sorry to bother you.

I recently ran into some problems with memory access when reading the source code [MEM_ACCESS_TYPE_TUP_DEF](https://github.com/accel-sim/gpgpu-sim_distribution/blob/a0c12f5d63504c67c8bdfb1a6cc689b4ab7867a6/src/abstract_hardware_model.h#L767C38-L767C38):

```c++
MA_TUP(L1_WRBK_ACC), MA_TUP(L2_WRBK_ACC), MA_TUP(L1_WR_ALLOC_R), MA_TUP(L2_WR_ALLOC_R)
```

I would like to kown what exactly these four types of memory access mean, are they "L1 write back access", "L2 write back access", "L1 write acclocation read", and "L2 write back allocation read"?

And I would like to kown under what circumstances they are used, or whether there are related papers or blogs or books that can help me understand this.

**Comment by JRPan** [comment]
Yes you are correct about the names. These are mainly for bookkeeping. And also in L2 these are used to determine the states of the access. 
For more about allocation policies, you can read Section III in https://arxiv.org/pdf/1810.07269.pdf. 
I would recommend reading the entire paper. 

Thanks,
Junrui
