### ISSUE TITLE
Jenkins workflow problem: incorrect path name 

### ISSUE THREAD

**Issue by FJShen** [accel-sim/accel-sim-framework#271]
Searching into the raw text log file of PR #270 reveals the use of path name `/racer_accel-sim-...`. 
E.g.: line 7 of the below excerpt taken from the raw text log file of PR #270 . 

```
Branch indexing
Connecting to https://api.github.com using a598d83b-9593-42fa-96f8-a789fff7b858
Connecting to https://api.github.com to check permissions of obtain list of tgrogers for accel-sim/accel-sim-framework
Obtained tracer.Jenkinsfile from 19282d74a60a6d0f3c7540b7203d055f4a1ece05+c1a12bcd9cb63c8abcfebd386e7365aa2ead1e53 (8939fbe551a4ab32e57b71b88c0143631ccf996d)
[Pipeline] Start of Pipeline
[Pipeline] node
Running on dgx-gpu01 in /home/tgrogers-raid/a/jenkin99/dgx-gpu01-jenkinshome/workspace/racer_accel-sim-framework_PR-270
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
using credential a598d83b-9593-42fa-96f8-a789fff7b858
```

**Comment by tgrogers** [comment]
Does this actually cause an error - jenkins may be doing some truncation to keep the folder name lengths sane.
If you look at: /home/tgrogers-raid/a/jenkin99/dgx-gpu01-jenkinshome/workspace/ (on tgrogers-raid) - does the racer directory actually exist?

**Comment by FJShen** [comment]
I do not know if this causes an error. The directory does exist under /home/tgrogers-raid/a/jenkin99/dgx-gpu01-jenkinshome/workspace/ on tgrogers-raid. I consider this an anomaly that has to be reported.

**Comment by tgrogers** [comment]
Ok, I think this is fine. I am going to close it. It's not an anomaly - just Jenkins trying to conserve characters.
