### ISSUE TITLE
Jenkins workflow problem: Link from Github to Jenkins server is not working

### ISSUE THREAD

**Issue by FJShen** [accel-sim/accel-sim-framework#272]
![image](https://github.com/accel-sim/accel-sim-framework/assets/50934207/55957186-4446-4773-86fe-5d3f02043253)

Clicking on the "details" link after `continuous-integration/jenkins/pr-merge — This commit looks good`  leads you to a page "Not Found". This issue is first reported in PR #270

**Comment by JRPan** [comment]
Jenkins deprecated. Replaced by Github Actions
