### ISSUE TITLE
Jenkins workflow problem: PTX mode was not tested in Jenkins CI flow

### ISSUE THREAD

**Issue by FJShen** [accel-sim/accel-sim-framework#274]
According to the log of the Jenkins CI test for PR #270 , PTX was not tested. I reached this conclusion by searching for "QV100-PTX" and not finding a hit in the raw log file. Issue first reported in PR #270.

**Comment by tgrogers** [comment]
https://tgrogers-pc01.ecn.purdue.edu/job/Accel-Sim/job/accel-sim-framework/job/dev/38/consoleFull

It's in there. What file are you not seeing it in?

**Comment by FJShen** [comment]
I was not seeing QV100-PTX in the exact log file for PR #270.  [https://tgrogers-pc01.ecn.purdue.edu/job/accel-sim-tracer/job/accel-sim-framework/view/change-requests/job/PR-270/1/consoleText](https://tgrogers-pc01.ecn.purdue.edu/job/accel-sim-tracer/job/accel-sim-framework/view/change-requests/job/PR-270/1/consoleText)

**Comment by tgrogers** [comment]
ahhh, ok - yes, this is the tracer test. We do not do PTX testing here. We should already be testing PTX 2x: once in the GitHub Actions @JRPan setup and once in the non-tracer regressions. However, looking at the non-tracer regressions, it looks as though they were not triggered for PR-270. 

https://tgrogers-pc01.ecn.purdue.edu/job/Accel-Sim/job/accel-sim-framework/view/change-requests/

I need to look into this and figure out what is going on with our two different Jenkins validations.

**Comment by JRPan** [comment]
Jenkins deprecated. Replaced by Github Actions.
