### ISSUE TITLE
generating trace files in DGX-1 V100

### ISSUE THREAD

**Issue by beneslami** [accel-sim/accel-sim-framework#283]
Hi. I'm trying to generate trace files of [Tartan benchmark suite](https://github.com/uuudown/Tartan), which is based on Multi-GPU system, with tracer-nvbit. I want to know if it is possible or not ? Because I encounter different errors related to post-processing step.

Thanks,

**Comment by JRPan** [comment]
The tracer cannot trace multi-gpu yet. We are working on it, and we have a prototype. But it's not good enough to be shared yet. 
Post-processing gives an error probably because the trace is corrupted.
