### ISSUE TITLE
Unable to Setup Environment for gpu_app_collection for Tracer tool

### ISSUE THREAD

**Issue by shkailas1** [accel-sim/accel-sim-framework#285]
I am unable to properly trace the Rodinia Functional Tests. 
I am running the code in a container provided for the demo in the Readme: accelsim/ubuntu-18.04_cuda-11:latest
![image](https://github.com/accel-sim/accel-sim-framework/assets/99767792/355e8d74-fddb-4c43-9860-621999f0cec5)

This container has cuda-11, which has been added to $PATH
In this container I am following the instructions for tracing the rodinia_2.0-ft tests.
After cloning the gpu-app-collection repo, and running the source command (source ./gpu-app-collection/src/setup_environment ), I receive many errors, may of them of the following format but with different .cu.o files:

g++: error: obj/x86_64/release/bandwidthTest.cu.o: No such file or directory

This is the end of the output:
![image](https://github.com/accel-sim/accel-sim-framework/assets/99767792/0b398303-e214-4b4d-82e6-b3fa6eddc72f)

For context, I have provided the outputs of the previous commands from the repo.
This is the output from install_nvbit.sh:
![image](https://github.com/accel-sim/accel-sim-framework/assets/99767792/40237d86-d262-4e60-9a4f-517e802470be)

These are output images from making the tool (make -C ./util/tracer_nvbit/):
![image](https://github.com/accel-sim/accel-sim-framework/assets/99767792/175adde6-633b-49f3-af76-5311c6caf706)
![image](https://github.com/accel-sim/accel-sim-framework/assets/99767792/511a93ef-35cf-4a5e-9a9d-00d0b1000e46)

This is the full error log from running the source command:
[error.log](https://github.com/accel-sim/accel-sim-framework/files/14452123/error.log)

Thank you for your help!

**Comment by JRPan** [comment]
It should be fine and can be ignored. Try to build the applications.
