### ISSUE TITLE
AccelWatch Segmentation Fault on example Rodinia_2.0-ft

### ISSUE THREAD

**Issue by shkailas1** [accel-sim/accel-sim-framework#291]
I am running into the issue where every benchmark in rodinia_2.0-ft is seg faulting. I generated the traces using my gpu (gtx 1080ti). I am also able to run AccelSim using those traces and generate statistics. I have been using the TITANX configuration (since both are pascal). However, when I try to do the AccelWatch example in the ReadMe, every benchmark seg faults (screenshot shows one, but all are of similar format). This occurs both when I tried the `-C GV100-Accelwattch_SASS_HW` and the `-C TITANX-Accelwattch_SASS_HW` flags. Could you please advise on what the issue may be. Thank you for your help!
![image](https://github.com/accel-sim/accel-sim-framework/assets/99767792/a37ffbe3-8b65-4aed-8f8d-3048879f52fb)
(ubuntu-18, cuda 11.0)
Using the `release` branch for accel-sim-framework and gpu-app-collection

**Comment by JRPan** [comment]
are you using the traces you collected with 1080ti?

You can use gdb to see which line is causing the SEGF
