### ISSUE TITLE
Extremely high memory usage problem

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#3]
Some apps in polybench require a high amount of memory. 

![image](https://user-images.githubusercontent.com/14326227/90152466-cd8a2c80-ddc2-11ea-99fe-13f2543c16f5.png)

(polybench-correlation also causes the same problem => Both are eventually killed)

Is this the limitation of accelsim caused by a large trace file?

I didn't hack the source code regarding reading the trace file and parsing commands.

But it seems that accelsim need to be modified to handle this issue.

**Comment by tgrogers** [comment]
Thanks for the note. We are aware of the memory issues in v1.0.0. The current dev branch (and pending release of v1.0.1) will reduce memory computing by 10x.

**Comment by allencho1222** [comment]
> Thanks for the note. We are aware of the memory issues in v1.0.0. The current dev branch (and pending release of v1.0.1) will reduce memory computing by 10x.
> […](#)
> Sent from my iPhone
> On Aug 13, 2020, at 11:16, allen ***@***.***> wrote: ﻿ Some apps in polybench require a high amount of memory. (polybench-correlation also causes the same problem) Is this the limitation of accelsim caused by a large trace file? I didn't hack the source code regarding reading the trace file and parsing commands. But it seems that accelsim need to be modified to handle this issue. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Th

**Comment by allencho1222** [comment]
@tgrogers Thank you for the reply. Let me pull the source code and I'll post the issue if found the problem.

**Comment by allencho1222** [comment]
@tgrogers Thank you for the reply. If you don't mind, could you tell me which commit in dev branch includes it?
