### ISSUE TITLE
clang-format isn't being properly enforced

### ISSUE THREAD

**Issue by barnes88** [accel-sim/accel-sim-framework#305]
I don't think the method setup in https://github.com/accel-sim/accel-sim-framework/pull/236 is properly enforcing clang-format, because the dev branch has already diverged quite a bit from the formatting (I ran it on the latest dev commit and there are quite a few changes https://github.com/barnes88/gpgpu-sim_distribution/tree/clang-format-6.4.24). This is annoying if you have your editor set to enforce formatting on save, because it causes a bunch of lines to be changed that you didn't edit.

Maybe we can have Jenkins run a formatting stage diff so we can reject PRs that aren't properly formatted. Or we need everyone in the lab to install the pre-commit hooks.

@FJShen

**Comment by tgrogers** [comment]
Yeah we used to have a format checker.
Please flag junrui to resurrect it. We have move to GitHub ci and away from
maintaining our own Jenkins server.

**Comment by JRPan** [comment]
Or I can spawn a job to run the format script before merge.

**Comment by FJShen** [comment]
Sorry for your inconvenience. Accel-Sim PR #236 (and GPGPU-Sim PR [60](https://github.com/accel-sim/gpgpu-sim_distribution/pull/60), which is still being reviewed)  was an one-shot commit that re-formatted the code. The configuration file (.pre-commit-config.yaml) for "pre-commit" is included in the PR, but so far we don't have anything automated.

**Comment by FJShen** [comment]
@JRPan do you have anything implemented for the automatic formatting?

**Comment by JRPan** [comment]
Should we do automatic formatting before merging? Or reject non-formatted PR and ask people to format it?

**Comment by barnes88** [comment]
I think having automatic formatting would be easiest, that way people don't have to worry about trying to match the version of clang-format
