### ISSUE TITLE
Compatibility with 3080

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#33]
Hi
Prior to dig into the problem, I would like to know if there is any issue or test with accel-sim and RTX3080? Is there any known issue with current accel-sim version and cuda 11.2? Since 3080 is sm_86, the minimum version of cuda is 11.1.

**Comment by mkhairy** [comment]
Hi,
Yes, there are problems, ampere RTX3080 is not supported yet.
For the traces, Nvidia's NVBIT does not support sm_86 architecture, so if you are trying to trace the ampere sm_86 card, it will fault. Please, see this issue on NVBIT github:
https://github.com/NVlabs/NVBit/issues/33

For the GPGPU-sim mode, some features, like copy-async are not supported yet.

Thanks!

**Comment by mahmoodn** [comment]
Thanks for that.
I would like to know what is the current status of the tuner? 
I am interested in planning to extend that for 3080.

**Comment by mkhairy** [comment]
yeah, the tuner will come out with the next release of accel-sim (1.2), by the end of this month.

**Comment by mahmoodn** [comment]
There is an update for NVBit. I would like to to know if adding Ampere support is tricky or not. As I looked the the frontend [readme](https://github.com/accel-sim/accel-sim-framework/tree/release/gpu-simulator) file, it seems that adding an Ampere ISA is enough. Is that right? Is that the starting point?

**Comment by mkhairy** [comment]
The Ampere's copy-async instruction needs tracer and GPGPU-sim model updates.
The tracer: we assume all the mem instruction has only one mem operand (load, store, etc,), whereas copy-async instruction has two mem operands (shared and global), so we have to update the trace to handle this.
The GPGPU-sim mode also needs to be updated to model/execute copy-async correctly. 
If your workloads do not have copy-async instructions, then, yeah, updating only the front-end should be okay for now.

**Comment by mkhairy** [comment]
Also, remember we need to add the new NVBit release. If you are going to do any of these features, please PR and push it in our repo and we will review and accept that,
