### ISSUE TITLE
Issue about job waiting

### ISSUE THREAD

**Issue by SYYtera** [accel-sim/accel-sim-framework#339]
Hello. I have a question about Accelsim stats.csv file.

I tried to simulate Accelsim and wrote the command
./util/job_launching/run_simulations.py -B rodinia_2.0-ft -C new_QV100-SASS -T ./hw_run/traces/device-0/11.0/ -N myTest

and all the work seemed to be done well.

Using configs: new_QV100-SASS
Benchmark: rodinia_2.0-ft
Run Subdir = new_QV100-SASS
Parameters =
#SASS
#SASS-Driven Accel-Sim

Base config file = /home/youngsoo/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_new_QV100/gpgpusim.config
Job 209 queued (backprop-rodinia-2.0-ft-4096___data_result_4096_txt QV100-SASS)
Job 210 queued (bfs-rodinia-2.0-ft-__data_graph4096_txt___data_graph4096_result_txt QV100-SASS)
Job 211 queued (hotspot-rodinia-2.0-ft-30_6_40___data_result_30_6_40_txt QV100-SASS)
Job 212 queued (heartwall-rodinia-2.0-ft-__data_test_avi_1___data_result_1_txt QV100-SASS)
Job 213 queued (lud-rodinia-2.0-ft-_v__b__i___data_64_dat QV100-SASS)
Job 214 queued (nw-rodinia-2.0-ft-128_10___data_result_128_10_txt QV100-SASS)
Job 215 queued (nn-rodinia-2.0-ft-__data_filelist_4_3_30_90___data_filelist_4_3_30_90_result_txt QV100-SASS)
Job 216 queued (pathfinder-rodinia-2.0-ft-1000_20_5___data_result_1000_20_5_txt QV100-SASS)
Job 217 queued (srad_v2-rodinia-2.0-ft-__data_matrix128x128_txt_0_127_0_127__5_2___data_result_matrix128x128_1_150_1_100__5_2_txt QV100-SASS)
Job 218 queued (streamcluster-rodinia-2.0-ft-3_6_16_1024_1024_100_none_output_txt_1___data_result_3_6_16_1024_1024_100_none_1_txt QV100-SASS)
ProcMan spawned [pid=18075]

But when I change my result to csv file, I found all of data is NA.

So I tried to monitor job stat, then

209             UNKNOWN                         backprop-rodinia-2.0    4096___data_result_4    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
210             UNKNOWN                         bfs-rodinia-2.0-ft      __data_graph4096_txt    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
211             UNKNOWN                         hotspot-rodinia-2.0-    30_6_40___data_resul    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
212             UNKNOWN                         heartwall-rodinia-2.    __data_test_avi_1___    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
213             UNKNOWN                         lud-rodinia-2.0-ft      _v__b__i___data_64_d    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
214             UNKNOWN                         nw-rodinia-2.0-ft       128_10___data_result    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
215             UNKNOWN                         nn-rodinia-2.0-ft       __data_filelist_4_3_    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
216             UNKNOWN                         pathfinder-rodinia-2    1000_20_5___data_res    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
217             UNKNOWN                         srad_v2-rodinia-2.0-    __data_matrix128x128    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
218             UNKNOWN                         streamcluster-rodini    3_6_16_1024_1024_100    accelsim-commit-f783    new_QV100-SASS                    0 0       WAITING_TO_RUN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Passed:0/20, No error:0/20, Failed/Error:0/20, Running:0/20, Waiting:20/20

all jobs are just waiting and it doesn't change.
How can I solve this issue? 
I've been trying to figure out the cause all day, but I haven't solved it at all. Please help me.

**Comment by JRPan** [comment]
try deleting files under `./util/logfiles` and `./util/procman` and try again.

**Comment by SYYtera** [comment]
The probelm has been solved just before by following your instruction.
Thank you!
