### ISSUE TITLE
Some instructions do not have active thread mask in the trace file.

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#37]
Below is a part of the trace file of ResNet-18 training from NVIDIA.

![image](https://user-images.githubusercontent.com/14326227/110612765-da91c180-81d3-11eb-8e84-dcb19fd8685e.png)

Currently, I'm using the trace generator of recent accelsim with TURING arch.

Is this bug?

**Comment by mkhairy** [comment]
Which CUDA version do you use? what the Nvbit version? are you using dev or release branch?
This might be normal as the nvbit reports the masked out instruction if the branch is not taken, or it can be a real bug?

**Comment by mkhairy** [comment]
Could you try this commit in the dev branch and see if this fixes the problem:
https://github.com/accel-sim/accel-sim-framework/commit/6e68a4378dc11d55b096f30e04801582e0ee896c

If the mask remains the same, then probably as I mentioned earlier, that the nvbit tracer reports not-taken branches as well, which is normal and the accel-sim simulator will ignore these instructions.

**Comment by allencho1222** [comment]
Thank you for the help.

I used CUDA 10.1, NVbit 1.5.3, and dev branch.

In addition, I already used the recent version of the trace generator that includes the commit you posted.
