### ISSUE TITLE
Instruction, LDSM, is not correctly set in trace-driven.cc

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#38]
There exist an opcode called LDSM.

However, trace-driven.cc ignores the opcode, LDSM, which causes assertion during the simulation.

**Comment by mkhairy** [comment]
we have fixed that in dev branch, the fixed commit is:
https://github.com/accel-sim/accel-sim-framework/commit/70a7f80678e5fb4906ebba524fd8d9643f92fa7f

Please, note that the LDSM requires specific handling at the GPGPU-sim frontend to generate the right addresses and have a longer latency than other normal LDS shared instructions, however, the overall accuracy that we have right now should still be acceptable. For further details, please see the ldmatrix PTX (LDSM SASS) explanation from here:
https://github.com/NVIDIA/cutlass/blob/master/media/docs/implicit_gemm_convolution.md
https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions-ldmatrix

**Comment by allencho1222** [comment]
Thank you for details, I applied the commit.
