### ISSUE TITLE
undefined instruction: F2FP.PACK_AB

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#39]
I met a following error while simulating deep learning training with TURING arch (CUDA 10.1, NVbit 1.5.3, traces are generated from 2080Ti):

![image](https://user-images.githubusercontent.com/14326227/110620613-8dfeb400-81dc-11eb-9630-8b83f55094b2.png)

It is easy to fix the error. However, which OP should be mapped to support F2FP instruction?

Is this just ALU_OP?

I couldn't find the details of the instruction.

**Comment by mkhairy** [comment]
Based on CUDA binary instrumentation, [here](https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#turing), the ``F2FP`` does not exist in Turing, and it was first introduced in Ampere. Are you sure you are tracing a Turing card? If yes, then probably Nvidia forgot to add this instruction in SM_75 SASS of turning documentation. In this case, you can consider it as uniform instruction and launched it to "SPECIALIZED_UNIT_4_OP".

**Comment by allencho1222** [comment]
I'm sure that the trace file was generated from 2080Ti, which is turing arch. 

I also found that F2FP does not exist in the documentation.

Thank you for the comment, and I'll do PR for the modification later.

**Comment by mkhairy** [comment]
Actually what was proposed in Ampere was ``UF2FP`` not ``F2FP``. So it is a normal ALU_OP, not uniform instruction as I mentioned earlier. Nvidia probably forgot to document this instruction. 
Yeah, please PR this modification in Turing ISA. Thanks!
