### ISSUE TITLE
load, store mismatch for OP_ATOMG, OP_RED, and OP_ATOM

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#40]
I found that OP_ATOMG, OP_RED, and OP_ATOM do not follow the OP described in `opcode.h`

![image](https://user-images.githubusercontent.com/14326227/111026054-98fb5380-842b-11eb-93c1-5813ffe691f6.png)

While these three OPs are STORE_OP,

![image](https://user-images.githubusercontent.com/14326227/111026066-a6b0d900-842b-11eb-8499-d0b276559e42.png)

memory_op is initialized to `memory_load`.

**Comment by mkhairy** [comment]
Hi, no this is not a bug. memory_op should be ignored by gpgu-sim when then it is atomic instruction. however, for some reason, when I changed it to store_op it was causing deadlock, so I just left it as memory_load. The important thing is that atomics are executed correctly in gpgpu-sim with these parameters, so it is not a bug.
