### ISSUE TITLE
GPGPU-Sim statistics in Accel-Sim

### ISSUE THREAD

**Issue by AjinkyaBankar** [accel-sim/accel-sim-framework#41]
How can I get all the GPGPU-Sim statistics such as kernel, CTA allocation to different shader cores, memory stats, and all GPGPU-Sim related stats while simulating benchmark applications in the Accel-Sim? Also, can we configure GPUWattch for the GPGPU-Sim while using the Accel-Sim frontend? Kindly help. Thanks.

**Comment by mkhairy** [comment]
As described on the readme of accel-sim [here](https://github.com/accel-sim/accel-sim-framework), you can do this by running the get_stats.py script as follows:
```
./util/job_launching/get_stats.py -R -k -K -B rodinia_2.0-ft -C QV100-SASS | tee per.kernel.stats.csv
```
