### ISSUE TITLE
Questions for functional units in GPGPU-sim

### ISSUE THREAD

**Issue by allencho1222** [accel-sim/accel-sim-framework#44]
It seems that GPGPU-sim regards one functional unit as 32 SIMD width units.

From one of SM designs (PASCAL architecture):

![image](https://user-images.githubusercontent.com/14326227/114353346-e47a5c00-9ba7-11eb-9af4-7abba38c9360.png)

Each SM is first divided into four sub-SMs and each sub-SM owns 8 SFU units.
(AFAIK, the unit shown in the figure corresponds to a single lane, not multiple lanes).

However, in GPGPU-sim, from the source code, I found that the number of functional units (**X**) specified in the configuration file indicates **X** * 32 Lanes.

Here, I have a question.
    
Sometimes, some architectures have a functional unit less than 32 lanes per SM. In this case, how to instantiate this kind of functional units? (For example, [pascal architecture has 4 DP units per SM](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8716300)) Is this just modeled by the latency of the functional unit?

**Comment by mkhairy** [comment]
Hello, we determine the width of the lanes by the initiation latency parameters. As shown below in Volta config, DP unit has an initiation latency of four, so each DP instruction will take four cycles to issue, thus the SIMD width is 32/4=8 (i.e. each DP unit has 8 lanes, and so one 8-width DP unit per scheduler). Similarly, the SFU unit has an initiation latency of 8, thus SFU lanes width is 32/8=4.

```
-ptx_opcode_latency_int 4,13,4,5,145,21
-ptx_opcode_initiation_int 2,2,2,2,8,4
-ptx_opcode_latency_fp 4,13,4,5,39
-ptx_opcode_initiation_fp 2,2,2,2,4
-ptx_opcode_latency_dp 8,19,8,8,330
-ptx_opcode_initiation_dp 4,4,4,4,130
-ptx_opcode_latency_sfu 100
-ptx_opcode_initiation_sfu 8
-ptx_opcode_latency_tesnor 64
-ptx_opcode_initiation_tensor 64
```
