### ISSUE TITLE
Simulated instructions

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#51]
Hi
I took Stencil and according to the nvbit tracer, there are about 760K instructions in the kernel
```
kernel 95 - _Z24block2D_hybrid_coarsen_xffPfS_iii - #thread-blocks 64,  kernel instructions 760284, total instructions 72987264
```
However, according to the accel-sim, the number of simulated instruction for that kernel is about 19M.
```
kernel_name = _Z24block2D_hybrid_coarsen_xffPfS_iii
kernel_launch_uid = 95
gpu_sim_cycle = 43170
gpu_sim_insn = 19821254
gpu_ipc =     459.1442
gpu_tot_sim_cycle = 4102406
gpu_tot_sim_insn = 1883019130
```
I guess the nvbit instruction tracer uses warp level statistics, however, 760K*32 is about 24M which is more than 19M.
Any idea about that?

**Comment by mkhairy** [comment]
the stencil might be irregular with less than 32 threads in warps are only active.
to ensure an accurate correlation, please read the source code of how we correlate the instructions in accel-sim correlator:
https://github.com/accel-sim/accel-sim-framework/blob/4c2bf09a79d6b57bb10fe1898700930a5dd5531f/util/plotting/correl_mappings.py#L194

As you can see, we select the metric "inst_issued" from the HW profiler and "gpgpu_n_tot_w_icount" from gpgpu-sim output.

**Comment by mahmoodn** [comment]
OK Thanks.
