### ISSUE TITLE
Compilation error on ubuntu 21.04. Solution inside

### ISSUE THREAD

**Issue by rodhuega** [accel-sim/accel-sim-framework#52]
Hi, I'm a new user of the framework. I have experienced a compilation error using ubuntu 21.04.
The problem is `unable to find string literal operator ‘operator"` for two lines of  `gpu-simulator/gpgpu-sim/build/gcc-/cuda-11020/release/cuda-sim/ptx_parser_decode.def`

Changing the lines 2 and 4 from

```
DEF(YYEOF,"YYEOF                     /* "end of file"  */")
DEF(YYUNDEF,"YYUNDEF                 /* "invalid token"  */")
```
to
```
DEF(YYEOF,"YYEOF                     /* END_OF_FILE  */")
DEF(YYUNDEF,"YYUNDEF                 /* INVALID_TOKEN  */")
```
solves the error.

This post is only to help any other users that might could face the same problem and may take this change into account for the next release.

**Comment by mkhairy** [comment]
ok, thanks. It is properly some compiler compatibility problem.

**Comment by tschwinge** [comment]
See <https://github.com/accel-sim/gpgpu-sim_distribution/pull/42> "Fixed regex for files generated by newer bison versions which break build from source".
