### ISSUE TITLE
Regarding installation and Trace Generation problems

### ISSUE THREAD

**Issue by NaveenDevulapally** [accel-sim/accel-sim-framework#53]
SIr,
I tried installing Accelsim by following the steps in the github. My problems are
1) So when i try to generate the traces for rodinia workload, it is not generating the traces by showing error that "Unable to open file: /home/ajinkya/accel-sim-framework/hw_run/traces/device-0/11.0/streamcluster-rodinia-2.0-ft/3_6_16_1024_1024_100_none_output_txt_1___data_result_3_6_16_1024_1024_100_none_1_txt/traces/kernelslist".

2) Other Major problem is that after restarting my system after installation. the system is not opening by showing the errors. 

My doubt is do we require graphics card to run the Accelsim

Waiting for the response

Thank you

**Comment by mkhairy** [comment]
Did you try to generate the traces from scratch or downloading it from our repo? If you tried to generate the traces, then yes you need to require a NVIDIA graphics card.

**Comment by NaveenDevulapally** [comment]
Thanks for the reply.

So now I am unable to get the traces from the ftp server ftp://ftp.ecn.purdue.edu/tgrogers/accel-sim/traces showing the connection timeout problem.

**Comment by mkhairy** [comment]
I double-check now and they are working. can you please check again?

**Comment by NaveenDevulapally** [comment]
I tried again now. But showing the same connection time out problem. Attaching the terminal output. please check once

https://drive.google.com/file/d/1bvau-khuqkdtl0pBoWMR6ax71WD_gzBY/view?usp=sharing

**Comment by mkhairy** [comment]
I can confirm it is working for me and my labmates. Could you please check that the FTP port is not blocked? and there is no firewall problem or something at your end that can block the FTP protocol? try a different machine and see. 
Check this for troubleshooting: https://www.siteground.com/kb/common-ftp-errors/

**Comment by NaveenDevulapally** [comment]
Thank you.

It is working with the other network. Right now, I am able to download the trace file.
