### ISSUE TITLE
Post trace processing memory consumption

### ISSUE THREAD

**Issue by mahmoodn** [accel-sim/accel-sim-framework#54]
It seems that post trace processing takes a lot of memory for an 37GB trace file, because it ends up with the following crash:
```
Processing file /....../kernel-54.trace
run.sh: line 2: 984473 Killed     
```
Is there any workaround for that? I wonder if that is related to opening the file at [this](https://github.com/accel-sim/accel-sim-framework/blob/release/util/tracer_nvbit/tracer_tool/traces-processing/post-traces-processing.cpp#L88) source line. The system has 32GB of physical memory.

**Comment by mkhairy** [comment]
Unfortunately, this is one of the pitfalls when it comes to traces is that it consumes large memory. You properly need to move a larger machine or increase your VM size.

**Comment by mahmoodn** [comment]
OK. More debug shows that the vector of vector ([here](https://github.com/accel-sim/accel-sim-framework/blob/release/util/tracer_nvbit/tracer_tool/traces-processing/post-traces-processing.cpp#L154)) becomes very very large. In fact open() has no problem. I can manually limit that to process chunks based on `tb_id` and pass over it multiple times. I have to see... Thanks.
