### ISSUE TITLE
Accel-sim is not deterministic

### ISSUE THREAD

**Issue by mkhairy** [accel-sim/accel-sim-framework#60]
It seems accel-sim gives different IPC/cycles for different runs. see below for more info
https://groups.google.com/g/accel-sim/c/aX2ATtqkhyM

**Comment by dsartzet** [comment]
Hello, do you may have any update on this?

**Comment by nothingface0** [comment]
I've been trying to reproduce this and, using the latest `release` build of Accel-Sim (commit [`2260456ea5e6a1420f5734f145a4b7d8ab1d4737`](https://github.com/accel-sim/accel-sim-framework/commit/2260456ea5e6a1420f5734f145a4b7d8ab1d4737)), and the latest `dev` build of `gpgpu-sim` (commit [`13c67115070dc2f0876254a790d0238073ca364a`](https://github.com/accel-sim/gpgpu-sim_distribution/commit/13c67115070dc2f0876254a790d0238073ca364a), `setup_environment` set to `release`) I can verify that I still get non-deterministic results. 

The test was done using:
- The **`rodinia_2.0-ft`** benchmark for QV100 in trace format (downloaded using `get-accel-sim-traces.py`), which was run **four times**.  This is the benchmark that is used as a failing case in the Google Groups link in the issue description.
- The **`rodinia-3.1`** benchmark for QV100 in trace format (also downloaded using `get-accel-sim-traces.py`), which was run **twice**. 

The comparison is made using:
- `gpu_tot_sim_cycle`

While it seems that the `rodinia_2.0-ft` benchmark does seem to have a deterministic result, the same does not apply for some apps in `rodinia-3.1`. Namely, the applications which seem to produce non-deterministic results are:
- `dwt2d-rodinia-3.1` (The `__data_rgb_bmp__d_1024x1024__f__5__l_3--final_kernel` configuration only): **0.24% difference in simulation cycles**
- `hotspot-rodinia-3.1` (both configurations): **2.05% and 0.42% difference in simulation cycles**
- `lud-rodinia-3.1` (both configurations): **0.05% and 0.15% difference in simulation cycles**
- `pathfinder-rodinia-3.1`: **0.33% difference in simulation cycles**

Full results can be seen in the **Detailed Results** section below. I can provide the whole stats files if needed.

## Steps to reproduce

### Full rodinia 3.1 benchmark 

```bash
./util/job_launching/run_simulations.py -B rodinia-3.1 -C QV100-SASS -T ./hw_run/rodinia-3.1/11.0/ -N rodinia3
./util/job_launching/monitor_func_test.py -v -N rodinia3  # May take ~2 days to complete
./util/job_launching/get_stats.py -N rodinia3 | tee rodinia3.csv
```

### Targeted rodinia 3.1 applications

E,g, for `hotspot` with the `1024_2_2___data_temp_1024___data_power_1024_output_out` configuration:

```bash
./gpu-simulator/bin/release/accel-sim.out -trace ./hw_run/rodinia-3.1/11.0/hotspot-rodinia-3.1/1024_2_2___data_temp_1024___data_power_1024_output_out/traces/kernelslist.g -config ./gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_QV100/gpgpusim.config -config ./gpu-simulator/configs/tested-cfgs/SM7_QV100/trace.config
```

## Detailed Results

### `rodinia_2.0-ft`

No differences in simulated cycles after 4 separate runs:

gpu_tot_sim_cycle\s*=\s*(.*) | Run1 | Run2 | Run3 | Run4
-- | -- | -- | -- | --
APPS | QV100-SASS | QV100-SASS | QV100-SASS | QV100-SASS
backprop-rodinia-2.0-ft/4096___data_result_4096_txt--final_kernel | 14936 | 14936 | 14936 | 14936
bfs-rodinia-2.0-ft/__data_graph4096_txt___data_graph4096_result_txt--final_kernel | 122465 | 122465 | 122465 | 122465
hotspot-rodinia-2.0-ft/30_6_40___data_result_30_6_40_txt--final_kernel | 54701 | 54701 | 54701 | 54701
heartwall-rodinia-2.0-ft/__data_test_avi_1___data_result_1_txt--final_kernel | 9224 | 9224 | 9224 | 9224
lud-rodinia-2.0-ft/_v__b__i___data_64_dat--final_kernel | 136901 | 136901 | 136901 | 136901
nw-rodinia-2.0-ft/128_10___data_result_128_10_txt--final_kernel | 138970 | 138970 | 138970 | 138970
nn-rodinia-2.0-ft/__data_filelist_4_3_30_90___data_filelist_4_3_30_90_result_txt--final_kernel | 30800 | 30800 | 30800 | 30800
pathfinder-rodinia-2.0-ft/1000_20_5___data_result_1000_20_5_txt--final_kernel | 31713 | 31713 | 31713 | 31713
srad_v2-rodinia-2.0-ft/__data_matrix128x128_txt_0_127_0_127__5_2___data_result_matrix128x128_1_150_1_100__5_2_txt--final_kernel | 29798 | 29798 | 29798 | 29798
streamcluster-rodinia-2.0-ft/3_6_16_1024_1024_100_none_output_txt_1___data_result_3_6_16_1024_1024_100_none_1_txt--final_kernel | 1149457 | 1149457 | 1149457 | 1149457

## `rodinia-3.1`

In **bold** the names of the apps which do not have consistent results.

gpu_tot_sim_cycle\s*=\s*(.*) | Run1 | Run2
-- | -- | --
APPS | QV100-SASS | QV100-SASS
b+tree-rodinia-3.1/file___data_mil_txt_command___data_command_txt--final_kernel | 128811 | 128811
backprop-rodinia-3.1/65536--final_kernel | 61543 | 61543
bfs-rodinia-3.1/__data_graph4096_txt--final_kernel | 122381 | 122381
bfs-rodinia-3.1/__data_graph65536_txt--final_kernel | 184110 | 184110
bfs-rodinia-3.1/__data_graph1MW_6_txt--final_kernel | 950694 | 950694
dwt2d-rodinia-3.1/__data_192_bmp__d_192x192__f__5__l_3--final_kernel | 72373 | 72373
**dwt2d-rodinia-3.1/__data_rgb_bmp__d_1024x1024__f__5__l_3--final_kernel** | 177990 | 177562
gaussian-rodinia-3.1/_f___data_matrix4_txt--final_kernel | 34254 | 34254
gaussian-rodinia-3.1/_s_16--final_kernel | 171092 | 171092
gaussian-rodinia-3.1/_f___data_matrix208_txt--final_kernel | 2498139 | 2498139
gaussian-rodinia-3.1/_s_64--final_kernel | 731847 | 731847
gaussian-rodinia-3.1/_s_256--final_kernel | 3127581 | 3127581
**hotspot-rodinia-3.1/512_2_2___data_temp_512___data_power_512_output_out--final_kernel** | 21684 | 21239
**hotspot-rodinia-3.1/1024_2_2___data_temp_1024___data_power_1024_output_out--final_kernel** | 62359 | 62100
hybridsort-rodinia-3.1/r--final_kernel | 16610894 | 16610894
hybridsort-rodinia-3.1/__data_500000_txt--final_kernel | 3359747 | 3359747
kmeans-rodinia-3.1/_o__i___data_28k_4x_features_txt--final_kernel | 433930 | 433930
kmeans-rodinia-3.1/_o__i___data_kdd_cup--final_kernel | 2684683 | 2684683
kmeans-rodinia-3.1/_o__i___data_819200_txt--final_kernel | 4250086 | 4250086
lavaMD-rodinia-3.1/_boxes1d_10--final_kernel | 5671205 | 5671205
**lud-rodinia-3.1/_s_256__v--final_kernel** | 503948 | 503665
**lud-rodinia-3.1/_i___data_512_dat--final_kernel** | 1066432 | 1068013
myocyte-rodinia-3.1/100_1_0--final_kernel | 169185720 | 169185720
nn-rodinia-3.1/__data_filelist_4__r_5__lat_30__lng_90--final_kernel | 6371 | 6371
nw-rodinia-3.1/2048_10--final_kernel | 2524210 | 2524210
particlefilter_float-rodinia-3.1/_x_128__y_128__z_10__np_1000--final_kernel | 3907294 | 3907294
particlefilter_naive-rodinia-3.1/_x_128__y_128__z_10__np_1000--final_kernel | 676172 | 676172
**pathfinder-rodinia-3.1/100000_100_20___result_txt--final_kernel** | 116198 | 116591
srad_v1-rodinia-3.1/100_0_5_502_458--final_kernel | 8150016 | 8150016

**Comment by ammrat13** [comment]
For RTX2060's configuration, I get nondeterministic results on `rodinia_2.0-ft`. My steps were
```bash
$ ./util/job_launching/run_simulations.py -c 8 -B rodinia_2.0-ft -C RTX2060 -T /traces/dl/rodinia_2.0-ft/11.2/ -N Clean0
$ ./util/job_launching/monitor_func_test.py -v
$ ./util/job_launching/get_stats.py -N Clean0 > Clean0.out
$ ./util/job_launching/run_simulations.py -c 8 -B rodinia_2.0-ft -C RTX2060 -T /traces/dl/rodinia_2.0-ft/11.2/ -N Clean1
$ ./util/job_launching/monitor_func_test.py -v
$ ./util/job_launching/get_stats.py -N Clean > Clean1.out
$ diff -ru Clean0.out Clean1.out
```
My results are shown below. All of the traces differ in cycles except for `bfs`.
|gpu_tot_sim_cycle\s*=\s*(.*)                                                                                                    |`Clean0`|`Clean1`|
|--------------------------------------------------------------------------------------------------------------------------------|--------|--------|
|backprop-rodinia-2.0-ft/4096___data_result_4096_txt--final_kernel                                                               |27380   |26978   |
|bfs-rodinia-2.0-ft/__data_graph4096_txt___data_graph4096_result_txt--final_kernel                                               |128635  |128635  |
|hotspot-rodinia-2.0-ft/30_6_40___data_result_30_6_40_txt--final_kernel                                                          |108656  |107971  |
|heartwall-rodinia-2.0-ft/__data_test_avi_1___data_result_1_txt--final_kernel                                                    |10595   |10593   |
|lud-rodinia-2.0-ft/_v__b__i___data_64_dat--final_kernel                                                                         |185324  |185784  |
|nw-rodinia-2.0-ft/128_10___data_result_128_10_txt--final_kernel                                                                 |134363  |134362  |
|nn-rodinia-2.0-ft/__data_filelist_4_3_30_90___data_filelist_4_3_30_90_result_txt--final_kernel                                  |38416   |38634   |
|pathfinder-rodinia-2.0-ft/1000_20_5___data_result_1000_20_5_txt--final_kernel                                                   |31969   |31974   |
|srad_v2-rodinia-2.0-ft/__data_matrix128x128_txt_0_127_0_127__5_2___data_result_matrix128x128_1_150_1_100__5_2_txt--final_kernel |39680   |38897   |
|streamcluster-rodinia-2.0-ft/3_6_16_1024_1024_100_none_output_txt_1___data_result_3_6_16_1024_1024_100_none_1_txt--final_kernel |1145973 |1144202 |

**Comment by MWHYNOT** [comment]
@nothingface0 Hello, sir, I wonder is the command `. /util/job_launching/run_simulations.py -B rodinia_2.0-ft -C QV100-SASS -T . /hw_run/traces/device-<device-num>/<cuda-version>/ -N myTest` running all the rodinia_2.0-ft benchmark suite using the simulator ?
and what is the purpose of -N myTest?

When I use the command `. /util/job_launching/run_simulations.py -B rodinia_2.0-ft -C QV100-SASS -T . /hw_run/traces/device-<device-num>/<cuda-version>/ -N myTest`, it always appears error:
`
Cannot resolve default server host 'torqueserver' - check server_name file.
qsub: cannot connect to server torqueserver (errno=15008) Access from host not allowed, or unknown host
Job  queued (backprop-rodinia-2.0-ft-4096___data_result_4096_txt QV100-PTX)
`

So I have to run the benchmark using the command `./justrun` in the `/accel-sim-framework/sim_run_11.2/bfs-rodinia-2.0-ft/__data_graph4096_txt___data_graph4096_result_txt/QV100-SASS/`

I would really appreciate it if you could give me some advice

**Comment by nothingface0** [comment]
@wyk216 please ask in the [Discussion forums](https://github.com/accel-sim/accel-sim-framework/discussions).
