### ISSUE TITLE
Segmentation fault: Rodinia trace generation

### ISSUE THREAD

**Issue by sana-damani** [accel-sim/accel-sim-framework#66]
Command: ./util/tracer_nvbit/run_hw_trace.py -B rodinia_2.0-ft -D 0 

Error:
run.sh: line 2: 10814 Segmentation fault      (core dumped) LD_PRELOAD=<path_to_accelsim>/accel-sim-framework/util/tracer_nvbit/tracer_tool/tracer_tool.so <path_to_accelsim>/accel-sim-framework/gpu-app-collection/src/..//bin/11.4/release/backprop-rodinia-2.0-ft 4096 ./data/result-4096.txt

Unable to open file: <path_to_accelsim>/accel-sim-framework/hw_run/traces/device-0/11.4/backprop-rodinia-2.0-ft/4096___data_result_4096_txt/traces/kernelslist

GPU: GP102

**Comment by mkhairy** [comment]
is the kernelslist file is already generated, please check the directory and see if the file exists?
Also, ensure that the program is running without the tracer?

**Comment by sana-damani** [comment]
There is a kernelslist.g file but no kernelslist.

I am able to generate a trace for other apps using the command "LD_PRELOAD=<path>/tracer_tool.so <application>" so this is no longer a blocker for me.
