### ISSUE TITLE
 No such file or directory /Turing_RTX2060/gpgpusim.config

### ISSUE THREAD

**Issue by ajavadinezhad** [accel-sim/accel-sim-framework#67]
Hello

I just followed the example of the repo. finally, I have succeeded to run the simulator. but when I want to change to the microarchitecture of GPU using config file I 've got an error. The command that I've used it's: 

`./util/job_launching/run_simulations.py -B rodinia-3.1 -C RTX2060-SASS -T ./hw_run/rodinia-3.1/11.0/ -N myTest`

the error that was thrown was:
accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/Turing_RTX2060/gpgpusim.config'

and its' seems alright because if we check below directory we can see : 
gpu-simulator/gpgpu-sim/configs/tested-cfgs

We have only these configs, None of them are Turing_RTX2060
SM3_KEPLER_TITAN  SM6_TITANX  SM75_RTX2060  SM7_QV100  SM7_TITANV

So it's cannot find this config. I appreciate it if you help me

best regards,
AJN

![Untitled](https://user-images.githubusercontent.com/23430715/134033011-25f08d05-eda3-467d-ad58-a8d22e14dbb2.png)

**Comment by mkhairy** [comment]
which branch do you use? I think this might be fixed in dev branch

**Comment by ajavadinezhad** [comment]
I use the release branch. Thanks, I will also check the dev branch.

**Comment by ajavadinezhad** [comment]
@mkhairy  
I checked. The problem is solved in the dev branch, Thanks.
