### ISSUE TITLE
Although the simulation is over, the main task is not gone.

### ISSUE THREAD

**Issue by ajavadinezhad** [accel-sim/accel-sim-framework#68]
Hello,

Based on the repo example you can monitor the status of the simulator, After the simulation has done, you can use the below command to collect the result 

./util/job_launching/get_stats.py -N myTest | tee stats.csv

I do the same and it was successful and I can see the result under the sim_run folder, but the problem is the task was successful but still you can see a task In the task manager (using top command ) of ubuntu and it's related to the accel-sim.

so what can I do about it? can I kill them manually? does it a bug or something?

I appreciated it if you help me.

Best regards,
AJN
![Screenshot 2021-09-21 171800](https://user-images.githubusercontent.com/23430715/134173131-360ef98e-b2da-4d71-80ef-b7fa2a39f79c.png)

**Comment by mkhairy** [comment]
could you try job_status.py and ensure all the workloads have finished?
./util/job_launching/job_status.py

**Comment by ajavadinezhad** [comment]
I already did that It's finished but still a task remained and I killed them manually.

![Screenshot 2021-09-21 212318](https://user-images.githubusercontent.com/23430715/134214370-68524853-e3ad-42a5-a7ee-88e92e182af4.png)
![Screenshot 2021-09-21 213216](https://user-images.githubusercontent.com/23430715/134215281-eb0ab616-723b-46fa-96b8-42c735cd58e9.png)

**Comment by ajavadinezhad** [comment]
Alright, I did check on another suite (parboil) and all tasks fade automatically. I think it's related to the Rodinia-3.1 suite.

**Comment by mkhairy** [comment]
there might rodinia workloads is still running or you launched something before and was not finished yet. Please kill the process manually and relaunch rodinia again from scratch and monitor the job_status regularly.

**Comment by ajavadinezhad** [comment]
@mkhairy  Thanks for your recommendation.  I relaunched Rodina and I did monitor regularly and it was worked correctly.
