### ISSUE TITLE
Fail in post-traces-processing large kernel with 

### ISSUE THREAD

**Issue by tino9900** [accel-sim/accel-sim-framework#69]
I am running Resnet18 single epoch single iteration b 256 on Accel-sim Trace simulation 

Among the kernel traces I have acquired, there were trace files with sizes bigger than 200GB.
Post-processing of the files failed with std:bad_alloc termination call.
Fortunately, kernel trace files with around 150GB worked!!! 

I was wondering if you were aware of the problem.
Would there be a way to solve this?

Thank you for your works in Accel-Sim.

![image](https://user-images.githubusercontent.com/59046433/135411694-7fd25561-6cff-4d2a-89d6-be60a6a6f83c.png)
![image](https://user-images.githubusercontent.com/59046433/135411620-84334946-733e-4608-ba83-f314fa741d4c.png)

**Comment by tino9900** [comment]
I am using CUDA11.0, Turing RTX2080Ti, cuDNN (x), pytorch 1.9.1+cu111, and ResNet from pytorch example.

**Comment by tino9900** [comment]
Nay I think I found the reason.
It was a problem due to my insufficient RAM size.

**Comment by masa-laboratory** [comment]
@tino9900  Hi, does cmd `LD_PRELOAD=./tracer_tool/tracer_tool.so pytorch_mnist_train.py` can generate the traces of pytorch?
