### ISSUE TITLE
How to run ptx code in accel-sim-framework?

### ISSUE THREAD

**Issue by XiaPZ** [accel-sim/accel-sim-framework#76]
Hi community, I tried to run ptx code other than sass code with accel-sim, I tried the command as below:
`./util/job_launching/run_simulations.py -B rodinia_2.0-ft -C RTX2060-PTX -N MyTest7`
but it seams something went wrong, when I monitor this run:

> failed job log written to /home/xx/accel-sim/accel-sim-framework/util/job_launching/../job_launching/logfiles/failed_job_log_sim_log.MyTest7.21.11.14-Sunday.txt  

> 
> Passed:9/10, No error:0/10, Failed/Error:1/10, Running:0/10, Waiting:0/10  
> Contents /home/xx/accel-sim/accel-sim-framework/util/job_launching/../job_launching/logfiles/failed_job_log_sim_log.MyTest7.21.11.14-Sunday.txt:  
> 69        	UNKNOWN                       	pathfinder-rodinia-2	1000_20_5___data_res	pathfinder-rodinia-2RTX2060-PT	UNKNOWN        	UNKNOWN	FUNC_TEST_FAILED              	                                                  	
> 
> pathfinder-rodinia-2.0-ft-1000_20_5___data_result_1000_20_5_txt--RTX2060-PTX. Status=FUNC_TEST_FAILED  
> Last 10 line of /home/xx/accel-sim/accel-sim-framework/util/job_launching/../../sim_run_10.2/pathfinder-rodinia-2.0-ft/1000_20_5___data_result_1000_20_5_txt/RTX2060-PTX/pathfinder-rodinia-2.0-ft-1000_20_5___data_result_1000_20_5_txt.gpgpu-sim_git-commit-90ec3399763d7c8512cfe7dc193473086c38ca38_modified_0.0.o69  
>
> FAILED  
>   
> 29 34 41 35 35 41 34 34 37 28 28 35 30 31 32 40 42 42 44 45 43 40 34 38 34 30 35 41 34 38 38 43 47 41 44 46 34 35 39 34 31 35 30 35 27 27 24 30 23 32 32 35 36 44 36 39 33 40 36 31 27 25 24 24 28 31 24 44 30 29 31 33 29 37 37 40 39 42 34 31 32 36 41 38 37 34 33 36 35 35 36 38 37 29 29 31 28 30 28 27 31 34 36 36 33 39 32 35 36 35 39 32 37 40 38 35 38 34 38 35 31 35 24 29 27 29 25 29 24 30 28 26 33 27 40 39 30 31 37 41 39 36 40 32 34 35 30 26 27 29 32 32 30 31 32 28 32 39 35 40 49 37 35 32 31 32 39 39 41 37 36 34 39 31 33 31 38 40 41 42 48 39 34 35 43 41 39 31 37 34 43 42 42 38 37 37 43 38 46 38 33 33 37 44 43 43 33 32 32 49 47 37 42 37 43 45 38 39 36 43 42 43 41 36 33 30 30 31 28 26 27 28 28 24 25 31 26 22 18 32 27 41 32 29 35 32 31 34 36 36 40 41 41 36 33 27 35 37 34 30 36 27 37 30 30 30 32 34 39 37 33 36 39 39 46 48 37 34 39 34 40 38 32 42 41 46 42 40 40 34 27 34 34 35 27 29 29 33 31 36 30 36 35 35 33 28 32 35 34 32 29 26 23 25 29 33 32 35 36 34 26 22 25 22 25 32 29 31 30 34 25 32 34 24 23 20 15 19 22 24 17 26 33 32 36 31 35 30 33 31 41 39 35 35 32 36 30 34 31 29 37 -475 -494 -496 -503 -497 -499 -502 -499 -501 -501 -500 -501 -503 -506 -505 -490 -473 39 35 34 42 38 41 37 44 34 26 33 32 32 37 37 30 36 31 36 42 39 38 35 31 29 35 38 34 36 35 31 40 45 39 40 40 38 40 37 33 39 33 38 42 41 37 35 44 42 38 35 31 36 39 45 46 47 50 37 41 37 40 35 29 35 32 35 31 30 34 41 37 41 38 40 41 40 39 45 43 45 38 38 37 40 36 34 42 44 41 36 35 33 40 39 34 35 41 37 29 32 37 37 34 35 35 44 41 36 39 42 41 41 39 34 37 39 37 36 41 45 42 34 36 47 43 42 38 37 38 34 41 38 43 34 40 32 32 38 35 42 37 34 35 40 32 35 40 36 35 26 28 24 24 29 21 26 30 23 28 25 29 34 26 29 22 29 28 28 32 24 25 24 23 29 22 29 35 40 29 32 23 29 30 31 33 34 41 36 33 39 35 38 37 31 36 29 31 33 35 31 37 36 36 32 27 32 31 34 37 40 39 35 34 36 37 37 38 35 37 44 31 32 37 31 38 38 41 37 37 35 42 38 40 48 36 37 40 34 42 38 40 35 29 33 30 31 33 31 41 34 39 31 40 39 35 41 32 34 23 32 30 29 26 29 31 31 36 33 40 42 42 42 36 41 28 27 23 28 29 23 24 30 29 28 31 30 34 26 27 26 26 38 33 30 29 31 27 28 26 30 30 21 29 24 39 32 30 32 36 32 38 37 38 40 40 38 40 37 43 46 41 47 48 45 40 40 37 33 37 34 35 40 39 34 32 40 39 36 34 37 40 48 44 39 37 45 44 39 40 32 35 38 31 36 37 42 40 46 38 49 41 39 41 39 42 43 36 41 27 30 31 30 27 29 29 35 36 39 35 31 32 30 34 36 37 32 29 30 36 36 36 44 44 43 37 40 44 43 39 37 38 42 48 48 34 37 40 42 35 34 32 38 35 35 33 39 43 39 38 34 38 36 30 30 34 32 31 33 31 35 42 41 35 38 37 41 50 45 40 44 39 45 38 41 32 41 30 29 34 40 34 38 44 48 47 46 42 39 44 39 38 38 40 36 43 33 33 36 33 31 31 28 36 32 38 38 34 27 33 29 26 31 39 30 33 42 39 33 27 31 34 31 31 37 33 37 35 36 38 39 36 34 30 37 38 39 45 36 31 32 26 23 32 31 31 42 36 34 38 38 38 35 29 29 30 27 42 36 36 30 37 34 35 31 38 36 41 39 37 35 26 26 23 21 29 30 22 25 23 31 41 40 35 32 36 41 36 36 40 30 34 35 33 35 42 34 37 40 36 38 33 33 32 38 34 34 35 33 36 37 31 39 45 44 35 39 34 27 32 30 29 30 37 31 34 28 27 24 23 19 26 20 24 27 30 30 23 27 25 21 22 26 27 29 38 41 41 37 37 45 48  
> 5 4 5 7 0 3 0 8 2 2 6 3 8 9 7 5 9 0 6 9 5 0 1 5 9 4 4 3 9 9 0 4 3 7 3 6 0 5 6 4 7 3 9 5 4 9 0 3 9 9 5 4 1 6 9 2 1 6 5 2 5 7 8 0 6 1 8 7 6 5 1 5 0 3 2 4 2 5 8 1 6 5 7 7 3 9 0 6 5 7 8 0 7 8 2 3 1 1 2 9 6 6 4 6 9 9 2 1 4 2 4 0 7 1 9 1 2 9 7 7 9 8 9 6 6 2 1 8 3 4 7 9 0 4 7 1 5 9 2 1 2 8 1 1 9 2 4 2 4 2 1 3 2 1 1 8 3 4 8 6 8 8 7 0 4 4 1 9 5 5 0 9 3 3 3 5 7 7 9 1 1 0 4 3 3 7 4 6 2 4 4 2 4 1 5 0 7 6 9 5 2 1 6 7 6 9 2 4 7 3 5 0 4 2 6 9 1 0 6 3 6 0 8 1 4 3 1 1 1 3 8 5 6 5 3 5 4 7 9 3 1 6 4 7 8 0 6 0 2 4 5 8 5 5 1 1 8 5 2 0 0 3 5 8 8 0 3 2 8 2 6 1 9 2 0 9 2 6 1 6 1 9 6 8 4 0 9 5 7 3 7 7 6 4 5 6 5 1 9 5 3 7 8 4 9 8 6 3 4 9 1 7 8 7 7 5 7 8 2 6 2 9 3 0 3 1 7 0 2 8 5 7 7 3 4 6 3 0 1 8 1 4 7 2 1 5 7 1 3 1 7 7 0 3 0 5 6 9 6 0 7 3 9 4 9 3 2 2 5 5 2 7 9 0 1 2 7 8 5 2 1 5 0 1 0 2 8 6 1 4 8 8 0 7 4 9 3 8 3 0 3 6 9 4 8 0 6 7 0 2 9 1 9 9 2 9 3 1 7 4 7 5 4 7 4 0 8 7 8 4 0 1 2 9 7 2 0 4 9 0 8 8 2 7 0 6 8 3 9 5 8 9 2 4 8 6 5 9 6 3 3 8 7 7 7 4 9 7 0 8 0 0 6 2 9 8 0 7 2 0 4 2 1 6 6 9 5 3 8 3 9 3 1 8 0 8 4 9 8 5 7 8 7 6 0 7 4 2 6 8 4 1 0 5 7 9 5 4 4 3 7 3 7 8 3 9 9 8 9 7 5 8 5 2 4 7 1 1 9 8 9 4 9 2 1 8 3 6 3 7 2 2 3 1 3 6 0 2 4 1 1 1 0 8 4 4 5 5 7 6 5 7 2 4 1 4 5 4 2 0 3 6 2 6 7 5 5 0 9 1 1 2 3 1 0 9 8 7 6 5 6 2 4 0 8 7 6 3 3 9 3 7 7 8 5 7 5 2 9 7 4 0 9 7 4 2 8 4 1 4 1 7 6 8 0 7 5 6 0 9 7 6 6 5 6 3 4 1 6 3 0 0 3 0 9 9 4 7 3 5 3 7 5 0 5 5 9 0 3 9 9 1 7 7 8 5 3 2 9 9 5 9 1 0 1 2 2 5 1 7 3 4 4 8 6 9 3 5 2 8 7 3 9 6 1 9 2 4 1 1 5 8 2 6 9 4 8 3 9 1 0 2 5 5 2 2 6 7 9 8 6 6 2 5 3 5 5 7 1 8 8 6 7 2 4 8 6 4 1 6 5 3 0 0 8 3 4 7 0 4 5 6 2 9 4 7 4 1 4 5 1 4 3 8 7 7 8 3 1 1 1 6 5 4 9 5 9 5 2 9 1 0 8 4 9 4 1 6 7 8 3 8 2 7 7 9 4 7 5 8 9 8 4 6 2 5 3 1 3 8 3 4 8 3 8 9 7 2 7 6 0 1 4 4 8 3 4 4 1 1 2 2 9 9 0 2 6 3 5 9 1 8 4 1 3 4 3 0 6 2 6 8 3 3 3 3 6 9 0 7 0 2 1 1 3 1 5 0 7 1 1 0 1 7 4 5 2 7 7 0 9 6 9 5 9 4 0 5 3 0 5 5 5 8 6 0 2 4 2 9 7 4 1 8 1 5 5 5 4 3 6 6 1 7 1 0 1 3 7 6 4 4 3 1 3 1 1 7 5 6 8 2 2 9 3 3 5 8 9 1 3 7 7 4 6 8 6 7 2 6 5 8 0 0 1 5 1 4 2 7 0 0 1 2 2 4 8 9 5 9 0 0 6 8 7 2 8 3 1 0 1 8 0 4 8 1 9 9 8 4  
> targetBlock:[246]  
> blockGrid:[5]  
> blockSize: 256  
> border:[5]  
> gridSize: [1000]  
> pyramidHeight: 5  
> 
>   
> Contents of /home/xx/accel-sim/accel-sim-framework/util/job_launching/../../sim_run_10.2/pathfinder-rodinia-2.0-ft/1000_20_5___data_result_1000_20_5_txt/RTX2060-PTX/pathfinder-rodinia-2.0-ft-1000_20_5___data_result_1000_20_5_txt.gpgpu-sim_git-commit-90ec3399763d7c8512cfe7dc193473086c38ca38_modified_0.0.e69  
> 
>   
> 
> 
>   
> All 10 Tests Done.  
> Something did not pass.  

So here is my question: how to run ptx code in accel-sim? And how to debug such failure.
By the way, does ptx mode also simulate performance as sass mode? Thanks!

**Comment by JRPan** [comment]
Hi, 

The way you were launching PTX seems correct. And according to what you included, 9 tests finished successfully. Only pathfinder failed. 
`Passed:9/10, No error:0/10, Failed/Error:1/10, Running:0/10, Waiting:0/10`

To debug pathfinder, there are two files you can look at:
```/home/xx/accel-sim/accel-sim-framework/util/job_launching/../../sim_run_10.2/pathfinder-rodinia-2.0-ft/1000_20_5___data_result_1000_20_5_txt/RTX2060-PTX/pathfinder-rodinia-2.0-ft-1000_20_5___data_result_1000_20_5_txt.gpgpu-sim_git-commit-90ec3399763d7c8512cfe7dc193473086c38ca38_modified_0.0.e69```
and
```/home/xx/accel-sim/accel-sim-framework/util/job_launching/../../sim_run_10.2/pathfinder-rodinia-2.0-ft/1000_20_5___data_result_1000_20_5_txt/RTX2060-PTX/pathfinder-rodinia-2.0-ft-1000_20_5___data_result_1000_20_5_txt.gpgpu-sim_git-commit-90ec3399763d7c8512cfe7dc193473086c38ca38_modified_0.0.o69```

The o69 is the output while e69 is the error output. Checking the last several lines of the files should give you an idea of the error. Also, both accel-sim and gpgpu-sim work with gdb.

If you need any further help, please feel free to copy the related output here.

**Comment by XiaPZ** [comment]
@JRPan Thanks for your answer, I will try with it!

**Comment by JRPan** [comment]
Closing this for now. If you have any further question, please feel free to reopen
