### ISSUE TITLE
Errors occurred when setting up gpu-app-collection

### ISSUE THREAD

**Issue by Beomjun-Kim** [accel-sim/accel-sim-framework#77]
When I performed "source ./gpu-app-collection/src/setup_environment" this command,

there were many errors similar to 'g++: error: obj/x86_64/release/convolutionSeparable.cu.o: No such file or directory'

Most of the errors were like this.

Also, there wer errors like 'imageSegmentationNPP.cpp:438:3: error: 'nppiGraphcutInitAlloc' was not declared in this scope nppiGraphcutInitAlloc(size, &pGraphcutState, pBuffer);' .

So I think it's because of missing files in obj/x86_64/release/

What should I do in this situation to fix problems?

**Comment by JRPan** [comment]
Hi, 

Could you please provide the exact steps to re-create the error? 
The [setup_environment file](https://github.com/accel-sim/gpu-app-collection/blob/release/src/setup_environment) does not have any build/compile command. Did you make any changes to the files?

Thank you.

**Comment by JRPan** [comment]
Closing this for now. If you have any further question, please feel free to reopen

**Comment by lixiaozhen0071** [comment]
> Hi,
> 
> Could you please provide the exact steps to re-create the error? The [setup_environment file](https://github.com/accel-sim/gpu-app-collection/blob/release/src/setup_environment) does not have any build/compile command. Did you make any changes to the files?
> 
> Thank you.

what should I change the setup_environment file.Thank you!

**Comment by JRPan** [comment]
Update: 

Sry I misunderstood the question. I thought the error was related to accel-sim's setup script. 
When sourcing `gpu-app-collection/src/setup_environment`, **errors are expected** and they are configured to be ignored. Please **ignore the errors and proceed to build the apps**. The apps should build successfully.
