### ISSUE TITLE
Unable to run AccelWattch

### ISSUE THREAD

**Issue by ishitachaturvedi** [accel-sim/accel-sim-framework#87]
I downloaded the traces using get-accel-sim-traces.py and built Accelwattch.
On trying to run AccelWattch using the command->

./util/job_launching/run_simulations.py -B rodinia_2.0-ft -C QV100-Accelwattch_SASS_SIM -T ./hw_run/rodinia_2.0-ft/11.0/nn-rodinia-2.0-ft/__data_filelist_4_3_30_90___data_filelist_4_3_30_90_result_txt/traces/ -N myTest

I am getting the error->

Could not find Accelwattch_SASS_SIM in defined xtraconfigs {'L1OFF': '-gmem_skip_L1D 1', 'FCFS': '-gpgpu_dram_scheduler 0', 'FRFCFS': '-gpgpu_dram_scheduler 1', 'BOOKSIM': '-network_mode 1 -inter_config_file config_volta_islip.icnt', 'PTXPLUS': '-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10', 'PAE': '-memory_partition_indexing 3', '128B': '-gpgpu_mem_addr_mapping dramid@7;00000000.00000000.00000000.00000000.0000RRRR.RRRRRRRR.RBBBCCCC.BCCSSSSS', 'L1ON': '-gmem_skip_L1D 0', '100M_INSN': '-gpgpu_max_insn 100000000', '5B_INSN': '-gpgpu_max_insn 5000000000', 'SASS': '#SASS-Driven Accel-Sim', '1B_INSN': '-gpgpu_max_insn 1000000000', 'PTX': '#PTX-Driven GPGPU-Sim', '64SM': '-gpgpu_n_clusters 64', '1132MHZ': '-gpgpu_clock_domains 1132.0:1132.0:1132.0:850.0', '2B_INSN': '-gpgpu_max_insn 2000000000', 'RANDOM': '-memory_partition_indexing 4', 'XOR': '-memory_partition_indexing 1', 'PWR_ENABLE': '-power_simulation_enabled 1', 'LOCALXBAR': '-network_mode 2 -icnt_in_buffer_limit 512  -icnt_out_buffer_limit 512  -icnt_subnets 2', 'IPOLY': '-memory_partition_indexing 2', 'VISUAL': '-visualizer_enabled 1', 'PTXPLUS_SM6': '-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 62 -gpgpu_ptx_force_min_capability 60', '256B': '-gpgpu_mem_addr_mapping dramid@8;00000000.00000000.00000000.00000000.0000RRRR.RRRRRRRR.RBBBCCCB.CCCSSSSS', 'RR': '-gpgpu_scheduler lrr', '1455MHZ': '-gpgpu_clock_domains 1455.0:1455.0:1455.0:850.0', 'COPYK': '-perf_sim_memcpy 1', 'FLUSHL1': '-gpgpu_flush_l1_cache 1', 'NCOPYK': '-perf_sim_memcpy 0', 'NORM': '-memory_partition_indexing 0', 'SM_2': '-gpgpu_ptx_force_max_capability 20'}
Traceback (most recent call last):
  File "./util/job_launching/run_simulations.py", line 368, in <module>
    configurations.append( ConfigurationSpec( config ) )
  File "./util/job_launching/run_simulations.py", line 41, in __init__
    def __init__(self, ( name, params, config_file ) ):
TypeError: 'NoneType' object is not iterable

Please help me with this. Thanks!

**Comment by JRPan** [comment]
The config you are using: `QV100-Accelwattch_SASS_SIM` is not defined. 
Standard configs are included here: 
https://github.com/accel-sim/accel-sim-framework/blob/release/util/job_launching/configs/define-standard-cfgs.yml

So the term `QV100-Accelwattch_SASS_SIM` is combining two configs: `QV100` and `Accelwattch_SASS_SIM` (configs connected with "-" are combined). But `Accelwattch_SASS_SIM` is not defined by default. 
If you just want to add an identifier, please take a look at the config `SASS`:
```
SASS:
    extra_params: "#SASS-Driven Accel-Sim"
```
You may also take a look at the comments in the file for details

Thanks

**Comment by JRPan** [comment]
Actually my bad. The config `Accelwattch_SASS_SIM` is defined in the file under release-accelwattch branch. Please check if you have this in your config file
https://github.com/accel-sim/accel-sim-framework/blob/release-accelwattch/util/job_launching/configs/define-standard-cfgs.yml#L153

**Comment by ishitachaturvedi** [comment]
My config file is different somehow I will pull and check. Thanks!

**Comment by ishitachaturvedi** [comment]
How do I check the status of the spawned jobs?

The command I used was -
./util/job_launching/run_simulations.py -B rodinia_2.0-ft -C QV100-Accelwattch_SASS_SIM -T hw_run/rodinia_2.0-ft/11.0/ -N myTest

The output was-
Cannot find a supported job management system. Spawning jobs locally.
Running Simulations with GPGPU-Sim built from 
accelsim-commit-f27c5430b80f8b73e4027c2c6d1a1db58dd4adea_modified_3.0
 
Using configs: QV100-Accelwattch_SASS_SIM
Benchmark: rodinia_2.0-ft
Run Subdir = QV100-Accelwattch_SASS_SIM
Parameters = 
#Accelwattch_SASS_SIM
-power_simulation_enabled 1 
-power_simulation_mode 0 
-accelwattch_xml_file accelwattch_sass_sim.xml

Base config file = /scratch/ishitac/gpgpusim-codes/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_QV100/gpgpusim.config
Job 1 queued (backprop-rodinia-2.0-ft-4096___data_result_4096_txt QV100-Accelwattch_SASS_SIM)
Job 2 queued (bfs-rodinia-2.0-ft-__data_graph4096_txt___data_graph4096_result_txt QV100-Accelwattch_SASS_SIM)
Job 3 queued (hotspot-rodinia-2.0-ft-30_6_40___data_result_30_6_40_txt QV100-Accelwattch_SASS_SIM)
Job 4 queued (heartwall-rodinia-2.0-ft-__data_test_avi_1___data_result_1_txt QV100-Accelwattch_SASS_SIM)
Job 5 queued (lud-rodinia-2.0-ft-_v__b__i___data_64_dat QV100-Accelwattch_SASS_SIM)
Job 6 queued (nw-rodinia-2.0-ft-128_10___data_result_128_10_txt QV100-Accelwattch_SASS_SIM)
Job 7 queued (nn-rodinia-2.0-ft-__data_filelist_4_3_30_90___data_filelist_4_3_30_90_result_txt QV100-Accelwattch_SASS_SIM)
Job 8 queued (pathfinder-rodinia-2.0-ft-1000_20_5___data_result_1000_20_5_txt QV100-Accelwattch_SASS_SIM)
Job 9 queued (srad_v2-rodinia-2.0-ft-__data_matrix128x128_txt_0_127_0_127__5_2___data_result_matrix128x128_1_150_1_100__5_2_txt QV100-Accelwattch_SASS_SIM)
Job 10 queued (streamcluster-rodinia-2.0-ft-3_6_16_1024_1024_100_none_output_txt_1___data_result_3_6_16_1024_1024_100_none_1_txt QV100-Accelwattch_SASS_SIM)
ProcMan spawned [pid=12057]

**Comment by JRPan** [comment]
Something similar to this:
`./util/job_launching/monitor_func_test.py -v -N myTest`

This is documented in the README.

**Comment by ishitachaturvedi** [comment]
Thanks!
Somehow Accelwattch crashed after the changes I made to GPGPU-Sim, is there an easy way to debug it?

**Comment by ishitachaturvedi** [comment]
As a follow up- GPGPU-Sim simulations do run with my changes.

**Comment by ishitachaturvedi** [comment]
Hi could do a debug run and the issue is that I need to use the get_opcode() in ptx_ir.h function for the run, but it does not work with traces.
Do you know a work around for this?
Thanks!

**Comment by JRPan** [comment]
Maybe you can check if this class [`warp_inst_t` ](https://github.com/accel-sim/gpgpu-sim_distribution/blob/6c9e13db93e4a1614f7401e9675c62ea40b65a3b/src/abstract_hardware_model.h#L1003) and [`inst_t`](https://github.com/accel-sim/gpgpu-sim_distribution/blob/6c9e13db93e4a1614f7401e9675c62ea40b65a3b/src/abstract_hardware_model.h#L1003) have what you are looking for.

**Comment by ishitachaturvedi** [comment]
It worked! Thanks!
