### ISSUE TITLE
Some issues with Pascal and probably a global bug

### ISSUE THREAD

**Issue by rodhuega** [accel-sim/accel-sim-framework#91]
Hi, I have been working with Pascal and I have detected some bugs after getting some traces of Rodinia 3.1 and Deepbench (used NVBit 1.5.5 in order to get working the tracer).

First of all, there are at least two instruction missed in `pascal_opcode.h` . These ones are: `{"FCMP", OpcodeChar(OP_FCMP, SP_OP)}` and `{"VADD", OpcodeChar(OP_VADD, INTP_OP)}`. Moreover, `OP_VADD,` is also necessary in `trace_opcode.h`. 

The first instruction can be found at [here](https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#maxwell-pascal). However, the second one no, but it stills be reported by the tracer.

The second issue is something that is strange that have never happened before, but I think that it can happen with any architecture. It is at `shader.cc` in `void pipelined_simd_unit::cycle()` and many Deepbench traces (for example `conv_bench train half 7 7 832 16 256 1 1 0 0 1 1`. It seems that it tries to dispatch an instruction to a register which is already occupied by another instruction (the bug fires when it tries to do some `XMAD`). I fixed in the following way (I don't know if it is the best way):

```
void pipelined_simd_unit::cycle() {
  if (!m_pipeline_reg[0]->empty()) {
    m_result_port->move_in(m_pipeline_reg[0]);
    assert(active_insts_in_pipeline > 0);
    active_insts_in_pipeline--;
  }
  if (active_insts_in_pipeline) {
    for (unsigned stage = 0; (stage + 1) < m_pipeline_depth; stage++)
      move_warp(m_pipeline_reg[stage], m_pipeline_reg[stage + 1]);
  }
  if (!m_dispatch_reg->empty()) {
    if (!m_dispatch_reg->dispatch_delay()) {
      int start_stage =
          m_dispatch_reg->latency - m_dispatch_reg->initiation_interval;
      if(m_pipeline_reg[start_stage]->empty()) // MOD. Begin. Fix Deepbench GTX1080TI
      {
        move_warp(m_pipeline_reg[start_stage], m_dispatch_reg);
        active_insts_in_pipeline++;
      } // MOD. End. Fix Deepbench GTX1080TI  
    }
  }
  occupied >>= 1;
}
```

**Comment by JRPan** [comment]
Hi, 

Thank you for pointing that out. For the missing instructions, could you please create a PR with the changes you made?

Also, you are also correct about the bug. It's a very old bug in gpgpu-sim. This could happen when you have different latencies to the same execution unit. 
Could you please create another PR for this one? This one should be for the backend [accel-sim/gpgpu-sim_distribution](https://github.com/accel-sim/gpgpu-sim_distribution). 
Please make sure you are merging into the dev branches. 

Thank you for your contribution again!

**Comment by rodhuega** [comment]
Hi, from what branches I should do this? dev?

**Comment by JRPan** [comment]
Yes please!

**Comment by rodhuega** [comment]
Hi, the PR are done [here](https://github.com/accel-sim/accel-sim-framework/pull/94) and [here](https://github.com/accel-sim/gpgpu-sim_distribution/pull/30)
