### ISSUE TITLE
Running accelwattch without traces

### ISSUE THREAD

**Issue by ishitachaturvedi** [accel-sim/accel-sim-framework#95]
How do I run accelwattch from GPGPUSim by running it on a program instead of using traces?

**Comment by JRPan** [comment]
Hi, 

to run Accel-Sim in PTX mode, you may remove the `-T` argument when running `run_simulation.py`. You may check the README in the dev branch. 
Sorry for the confusion. This instruction will be included in the next release.

Thanks
